/*
 * File: app/store/combo/LoginStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.combo.LoginStore', {
    extend: 'Ext.data.Store',

    requires: [
        'FrontHPApp.model.LoginModel',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'combo.LoginStore',
            model: 'FrontHPApp.model.LoginModel',
            data: [
                {
                    UserName: 'sed',
                    Password: 'jGUUq2zWEY'
                },
                {
                    UserName: 'nostrum',
                    Password: '5p5c7dhi8k'
                },
                {
                    UserName: 'nam',
                    Password: 'MSBxwykBswty'
                },
                {
                    UserName: 'amet',
                    Password: 'AcOaQjK7Hg'
                },
                {
                    UserName: 'veniam',
                    Password: '5w0Zleh9ab'
                },
                {
                    UserName: 'nemo',
                    Password: '2DalQ5f'
                },
                {
                    UserName: 'alias',
                    Password: 'YDity7ZyD6oO'
                },
                {
                    UserName: 'ullam',
                    Password: 'nFY6vEGnab'
                },
                {
                    UserName: 'aspernatur',
                    Password: 'gwVRkWH'
                },
                {
                    UserName: 'dicta',
                    Password: '3TWwtlT2'
                }
            ],
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});