/*
 * File: app/store/checkPaperModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.checkPaperModels', {
    extend: 'Ext.data.Store',
    alias: 'store.checkpapermodels',

    requires: [
        'FrontHPApp.model.CheckPaperModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 15,
            storeId: 'checkPaperModels',
            model: 'FrontHPApp.model.CheckPaperModel',
            data: [
                {
                    RequestNo: 954,
                    RequestDate: '7/6/2009',
                    IdApprove: 951,
                    CitizenId: 917,
                    CusName: 'ducimus',
                    TypeLoan: 'optio',
                    BranchName: 'ut',
                    National: 'in',
                    Doc1: 'et',
                    Doc2: 'assumenda',
                    Doc3: 'expedita',
                    ResultDoc: 'error',
                    Remark: 'quo'
                },
                {
                    RequestNo: 715,
                    RequestDate: '8/9/2012',
                    IdApprove: 286,
                    CitizenId: 150,
                    CusName: 'deleniti',
                    TypeLoan: 'enim',
                    BranchName: 'repudiandae',
                    National: 'delectus',
                    Doc1: 'perspiciatis',
                    Doc2: 'iste',
                    Doc3: 'incidunt',
                    ResultDoc: 'est',
                    Remark: 'neque'
                },
                {
                    RequestNo: 295,
                    RequestDate: '9/1/2007',
                    IdApprove: 997,
                    CitizenId: 489,
                    CusName: 'impedit',
                    TypeLoan: 'autem',
                    BranchName: 'officia',
                    National: 'magnam',
                    Doc1: 'qui',
                    Doc2: 'et',
                    Doc3: 'suscipit',
                    ResultDoc: 'rerum',
                    Remark: 'unde'
                },
                {
                    RequestNo: 397,
                    RequestDate: '12/23/2007',
                    IdApprove: 562,
                    CitizenId: 28,
                    CusName: 'sint',
                    TypeLoan: 'quos',
                    BranchName: 'accusamus',
                    National: 'ut',
                    Doc1: 'totam',
                    Doc2: 'nostrum',
                    Doc3: 'omnis',
                    ResultDoc: 'sed',
                    Remark: 'sed'
                },
                {
                    RequestNo: 607,
                    RequestDate: '6/17/2013',
                    IdApprove: 774,
                    CitizenId: 469,
                    CusName: 'dolorum',
                    TypeLoan: 'et',
                    BranchName: 'tenetur',
                    National: 'omnis',
                    Doc1: 'aliquid',
                    Doc2: 'minus',
                    Doc3: 'iste',
                    ResultDoc: 'deleniti',
                    Remark: 'tempora'
                },
                {
                    RequestNo: 406,
                    RequestDate: '8/24/2007',
                    IdApprove: 595,
                    CitizenId: 899,
                    CusName: 'aliquid',
                    TypeLoan: 'dicta',
                    BranchName: 'vitae',
                    National: 'error',
                    Doc1: 'quod',
                    Doc2: 'repellendus',
                    Doc3: 'atque',
                    ResultDoc: 'porro',
                    Remark: 'consequuntur'
                },
                {
                    RequestNo: 297,
                    RequestDate: '12/6/2006',
                    IdApprove: 38,
                    CitizenId: 274,
                    CusName: 'laborum',
                    TypeLoan: 'earum',
                    BranchName: 'magnam',
                    National: 'eligendi',
                    Doc1: 'corrupti',
                    Doc2: 'vel',
                    Doc3: 'dolor',
                    ResultDoc: 'aut',
                    Remark: 'non'
                },
                {
                    RequestNo: 126,
                    RequestDate: '1/23/2003',
                    IdApprove: 923,
                    CitizenId: 573,
                    CusName: 'et',
                    TypeLoan: 'quia',
                    BranchName: 'fuga',
                    National: 'dolorum',
                    Doc1: 'tenetur',
                    Doc2: 'quos',
                    Doc3: 'aut',
                    ResultDoc: 'ut',
                    Remark: 'veritatis'
                },
                {
                    RequestNo: 901,
                    RequestDate: '1/22/2012',
                    IdApprove: 70,
                    CitizenId: 576,
                    CusName: 'omnis',
                    TypeLoan: 'sit',
                    BranchName: 'harum',
                    National: 'sed',
                    Doc1: 'consequuntur',
                    Doc2: 'suscipit',
                    Doc3: 'voluptatibus',
                    ResultDoc: 'nihil',
                    Remark: 'cumque'
                },
                {
                    RequestNo: 376,
                    RequestDate: '9/26/2001',
                    IdApprove: 590,
                    CitizenId: 658,
                    CusName: 'et',
                    TypeLoan: 'reiciendis',
                    BranchName: 'non',
                    National: 'voluptatum',
                    Doc1: 'sit',
                    Doc2: 'ut',
                    Doc3: 'quod',
                    ResultDoc: 'quasi',
                    Remark: 'et'
                },
                {
                    RequestNo: 794,
                    RequestDate: '1/13/2013',
                    IdApprove: 135,
                    CitizenId: 368,
                    CusName: 'esse',
                    TypeLoan: 'exercitationem',
                    BranchName: 'consequatur',
                    National: 'dolor',
                    Doc1: 'incidunt',
                    Doc2: 'sed',
                    Doc3: 'nemo',
                    ResultDoc: 'aperiam',
                    Remark: 'provident'
                },
                {
                    RequestNo: 68,
                    RequestDate: '7/3/2006',
                    IdApprove: 925,
                    CitizenId: 44,
                    CusName: 'est',
                    TypeLoan: 'velit',
                    BranchName: 'accusantium',
                    National: 'minus',
                    Doc1: 'nam',
                    Doc2: 'quis',
                    Doc3: 'omnis',
                    ResultDoc: 'qui',
                    Remark: 'et'
                },
                {
                    RequestNo: 819,
                    RequestDate: '9/16/2007',
                    IdApprove: 770,
                    CitizenId: 248,
                    CusName: 'odit',
                    TypeLoan: 'earum',
                    BranchName: 'harum',
                    National: 'ut',
                    Doc1: 'enim',
                    Doc2: 'aut',
                    Doc3: 'dolore',
                    ResultDoc: 'nemo',
                    Remark: 'quae'
                },
                {
                    RequestNo: 976,
                    RequestDate: '9/5/2003',
                    IdApprove: 664,
                    CitizenId: 315,
                    CusName: 'rerum',
                    TypeLoan: 'dolorem',
                    BranchName: 'saepe',
                    National: 'dolorem',
                    Doc1: 'exercitationem',
                    Doc2: 'praesentium',
                    Doc3: 'voluptas',
                    ResultDoc: 'qui',
                    Remark: 'numquam'
                },
                {
                    RequestNo: 967,
                    RequestDate: '5/11/2005',
                    IdApprove: 504,
                    CitizenId: 271,
                    CusName: 'unde',
                    TypeLoan: 'quas',
                    BranchName: 'eos',
                    National: 'necessitatibus',
                    Doc1: 'ab',
                    Doc2: 'nulla',
                    Doc3: 'unde',
                    ResultDoc: 'quis',
                    Remark: 'in'
                },
                {
                    RequestNo: 347,
                    RequestDate: '7/25/2007',
                    IdApprove: 21,
                    CitizenId: 179,
                    CusName: 'et',
                    TypeLoan: 'sit',
                    BranchName: 'quibusdam',
                    National: 'maiores',
                    Doc1: 'sequi',
                    Doc2: 'nesciunt',
                    Doc3: 'repudiandae',
                    ResultDoc: 'est',
                    Remark: 'et'
                },
                {
                    RequestNo: 13,
                    RequestDate: '8/11/2011',
                    IdApprove: 209,
                    CitizenId: 103,
                    CusName: 'ut',
                    TypeLoan: 'dolorem',
                    BranchName: 'in',
                    National: 'omnis',
                    Doc1: 'veniam',
                    Doc2: 'aut',
                    Doc3: 'recusandae',
                    ResultDoc: 'enim',
                    Remark: 'autem'
                },
                {
                    RequestNo: 864,
                    RequestDate: '5/9/2010',
                    IdApprove: 681,
                    CitizenId: 200,
                    CusName: 'soluta',
                    TypeLoan: 'eum',
                    BranchName: 'asperiores',
                    National: 'commodi',
                    Doc1: 'adipisci',
                    Doc2: 'consequatur',
                    Doc3: 'beatae',
                    ResultDoc: 'voluptate',
                    Remark: 'nesciunt'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});