/*
 * File: app/store/commitinSpecialModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.commitinSpecialModels', {
    extend: 'Ext.data.Store',
    alias: 'store.commitinspecialmodels',

    requires: [
        'FrontHPApp.model.CommitinSpecialModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'commitinSpecialModels',
            model: 'FrontHPApp.model.CommitinSpecialModel',
            data: [
                {
                    ID: 22,
                    EmployeeName: 'voluptatem',
                    TypeAgent: 'maxime',
                    TypePromote: 'occaecati',
                    Transfer: 933.29,
                    Withholding: 774.52,
                    'Amount Include VAT': 962.83,
                    'Loan Include VAT': 996.3,
                    VAT: 997.54,
                    'W/H TAX': 243.82,
                    'Net Paid': 757.34
                },
                {
                    ID: 582,
                    EmployeeName: 'sequi',
                    TypeAgent: 'porro',
                    TypePromote: 'quos',
                    Transfer: 229.18,
                    Withholding: 642.71,
                    'Amount Include VAT': 72.98,
                    'Loan Include VAT': 531.1,
                    VAT: 619.93,
                    'W/H TAX': 454.59,
                    'Net Paid': 908.37
                },
                {
                    ID: 530,
                    EmployeeName: 'aspernatur',
                    TypeAgent: 'impedit',
                    TypePromote: 'dolore',
                    Transfer: 814.18,
                    Withholding: 898.34,
                    'Amount Include VAT': 885.54,
                    'Loan Include VAT': 906.04,
                    VAT: 687.55,
                    'W/H TAX': 212.97,
                    'Net Paid': 679.97
                },
                {
                    ID: 514,
                    EmployeeName: 'est',
                    TypeAgent: 'error',
                    TypePromote: 'voluptatibus',
                    Transfer: 473.48,
                    Withholding: 542.5,
                    'Amount Include VAT': 873.48,
                    'Loan Include VAT': 814.83,
                    VAT: 853.56,
                    'W/H TAX': 538.04,
                    'Net Paid': 354.42
                },
                {
                    ID: 734,
                    EmployeeName: 'architecto',
                    TypeAgent: 'ea',
                    TypePromote: 'molestiae',
                    Transfer: 358.15,
                    Withholding: 736.43,
                    'Amount Include VAT': 108.8,
                    'Loan Include VAT': 768.97,
                    VAT: 8.57,
                    'W/H TAX': 814.13,
                    'Net Paid': 786.37
                },
                {
                    ID: 716,
                    EmployeeName: 'nobis',
                    TypeAgent: 'ducimus',
                    TypePromote: 'qui',
                    Transfer: 75.62,
                    Withholding: 47.54,
                    'Amount Include VAT': 270.8,
                    'Loan Include VAT': 109.63,
                    VAT: 417.02,
                    'W/H TAX': 953.04,
                    'Net Paid': 543.56
                },
                {
                    ID: 689,
                    EmployeeName: 'corporis',
                    TypeAgent: 'unde',
                    TypePromote: 'qui',
                    Transfer: 429.62,
                    Withholding: 480.68,
                    'Amount Include VAT': 341.65,
                    'Loan Include VAT': 273.34,
                    VAT: 336.81,
                    'W/H TAX': 966.99,
                    'Net Paid': 133.31
                },
                {
                    ID: 973,
                    EmployeeName: 'rem',
                    TypeAgent: 'ipsam',
                    TypePromote: 'vitae',
                    Transfer: 801.21,
                    Withholding: 365.53,
                    'Amount Include VAT': 443.09,
                    'Loan Include VAT': 23.3,
                    VAT: 997.1,
                    'W/H TAX': 141.16,
                    'Net Paid': 88.37
                },
                {
                    ID: 49,
                    EmployeeName: 'pariatur',
                    TypeAgent: 'maxime',
                    TypePromote: 'non',
                    Transfer: 991.32,
                    Withholding: 441.08,
                    'Amount Include VAT': 462.46,
                    'Loan Include VAT': 150.56,
                    VAT: 902.94,
                    'W/H TAX': 881.01,
                    'Net Paid': 27.87
                },
                {
                    ID: 767,
                    EmployeeName: 'vero',
                    TypeAgent: 'quaerat',
                    TypePromote: 'numquam',
                    Transfer: 577.31,
                    Withholding: 984.22,
                    'Amount Include VAT': 643.56,
                    'Loan Include VAT': 990.71,
                    VAT: 789.36,
                    'W/H TAX': 42.17,
                    'Net Paid': 278.39
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});