/*
 * File: app/store/incomeOtherModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.incomeOtherModels', {
    extend: 'Ext.data.Store',
    alias: 'store.incomeothermodels',

    requires: [
        'FrontHPApp.model.IncomeOtherModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'incomeOtherModels',
            model: 'FrontHPApp.model.IncomeOtherModel',
            data: [
                {
                    IncomeMain_id: 81.59,
                    IncomeOther_id: 'quia',
                    name: 'omnis'
                },
                {
                    IncomeMain_id: 354.72,
                    IncomeOther_id: 'dolor',
                    name: 'commodi'
                },
                {
                    IncomeMain_id: 729.78,
                    IncomeOther_id: 'neque',
                    name: 'sunt'
                },
                {
                    IncomeMain_id: 760.46,
                    IncomeOther_id: 'laboriosam',
                    name: 'ducimus'
                },
                {
                    IncomeMain_id: 938.43,
                    IncomeOther_id: 'quaerat',
                    name: 'eveniet'
                },
                {
                    IncomeMain_id: 139.61,
                    IncomeOther_id: 'minima',
                    name: 'aut'
                },
                {
                    IncomeMain_id: 548.62,
                    IncomeOther_id: 'magni',
                    name: 'cumque'
                },
                {
                    IncomeMain_id: 54.3,
                    IncomeOther_id: 'similique',
                    name: 'et'
                },
                {
                    IncomeMain_id: 83.19,
                    IncomeOther_id: 'aut',
                    name: 'fugiat'
                },
                {
                    IncomeMain_id: 806.11,
                    IncomeOther_id: 'cupiditate',
                    name: 'ex'
                },
                {
                    IncomeMain_id: 335,
                    IncomeOther_id: 'corrupti',
                    name: 'tempore'
                },
                {
                    IncomeMain_id: 515.64,
                    IncomeOther_id: 'enim',
                    name: 'voluptas'
                },
                {
                    IncomeMain_id: 468.84,
                    IncomeOther_id: 'consequatur',
                    name: 'et'
                },
                {
                    IncomeMain_id: 491.69,
                    IncomeOther_id: 'ab',
                    name: 'voluptates'
                },
                {
                    IncomeMain_id: 335.77,
                    IncomeOther_id: 'autem',
                    name: 'id'
                },
                {
                    IncomeMain_id: 101.39,
                    IncomeOther_id: 'est',
                    name: 'ut'
                },
                {
                    IncomeMain_id: 735.15,
                    IncomeOther_id: 'dicta',
                    name: 'molestiae'
                },
                {
                    IncomeMain_id: 25.35,
                    IncomeOther_id: 'quia',
                    name: 'non'
                },
                {
                    IncomeMain_id: 38.54,
                    IncomeOther_id: 'unde',
                    name: 'qui'
                },
                {
                    IncomeMain_id: 968.13,
                    IncomeOther_id: 'maiores',
                    name: 'minima'
                },
                {
                    IncomeMain_id: 105.9,
                    IncomeOther_id: 'harum',
                    name: 'sunt'
                },
                {
                    IncomeMain_id: 966.77,
                    IncomeOther_id: 'explicabo',
                    name: 'quia'
                },
                {
                    IncomeMain_id: 916.02,
                    IncomeOther_id: 'voluptatem',
                    name: 'commodi'
                },
                {
                    IncomeMain_id: 828.12,
                    IncomeOther_id: 'maiores',
                    name: 'cumque'
                },
                {
                    IncomeMain_id: 266.8,
                    IncomeOther_id: 'aliquam',
                    name: 'quo'
                },
                {
                    IncomeMain_id: 624,
                    IncomeOther_id: 'ex',
                    name: 'voluptas'
                },
                {
                    IncomeMain_id: 704.07,
                    IncomeOther_id: 'aut',
                    name: 'quis'
                },
                {
                    IncomeMain_id: 609.76,
                    IncomeOther_id: 'sint',
                    name: 'illum'
                },
                {
                    IncomeMain_id: 485.45,
                    IncomeOther_id: 'nihil',
                    name: 'dolorum'
                },
                {
                    IncomeMain_id: 584.61,
                    IncomeOther_id: 'rerum',
                    name: 'alias'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});