/*
 * File: app/store/marketModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.marketModels', {
    extend: 'Ext.data.Store',
    alias: 'store.marketmodels',

    requires: [
        'FrontHPApp.model.MarketModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'marketModels',
            model: 'FrontHPApp.model.MarketModel',
            data: [
                {
                    id: 946,
                    codeMarket: 738,
                    nameMarket: 'debitis',
                    tel: 'harum'
                },
                {
                    id: 334,
                    codeMarket: 641,
                    nameMarket: 'nisi',
                    tel: 'minima'
                },
                {
                    id: 299,
                    codeMarket: 22,
                    nameMarket: 'omnis',
                    tel: 'sed'
                },
                {
                    id: 82,
                    codeMarket: 772,
                    nameMarket: 'repellat',
                    tel: 'voluptatem'
                },
                {
                    id: 687,
                    codeMarket: 910,
                    nameMarket: 'debitis',
                    tel: 'ratione'
                },
                {
                    id: 107,
                    codeMarket: 891,
                    nameMarket: 'culpa',
                    tel: 'culpa'
                },
                {
                    id: 269,
                    codeMarket: 335,
                    nameMarket: 'qui',
                    tel: 'veniam'
                },
                {
                    id: 290,
                    codeMarket: 983,
                    nameMarket: 'sed',
                    tel: 'doloremque'
                },
                {
                    id: 665,
                    codeMarket: 454,
                    nameMarket: 'qui',
                    tel: 'qui'
                },
                {
                    id: 92,
                    codeMarket: 800,
                    nameMarket: 'id',
                    tel: 'dolores'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});