/*
 * File: app/store/occupationGroupModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.occupationGroupModels', {
    extend: 'Ext.data.Store',
    alias: 'store.occupationgroupmodels',

    requires: [
        'FrontHPApp.model.OccupationGroupModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'occupationGroupModels',
            model: 'FrontHPApp.model.OccupationGroupModel',
            data: [
                {
                    'OccupationCatelogy_id  ': 'saepe',
                    OccupationGroup_id: 656,
                    name: 'voluptatem'
                },
                {
                    'OccupationCatelogy_id  ': 'nesciunt',
                    OccupationGroup_id: 480,
                    name: 'et'
                },
                {
                    'OccupationCatelogy_id  ': 'sed',
                    OccupationGroup_id: 231,
                    name: 'cupiditate'
                },
                {
                    'OccupationCatelogy_id  ': 'est',
                    OccupationGroup_id: 932,
                    name: 'sapiente'
                },
                {
                    'OccupationCatelogy_id  ': 'velit',
                    OccupationGroup_id: 26,
                    name: 'sed'
                },
                {
                    'OccupationCatelogy_id  ': 'occaecati',
                    OccupationGroup_id: 795,
                    name: 'at'
                },
                {
                    'OccupationCatelogy_id  ': 'eum',
                    OccupationGroup_id: 20,
                    name: 'repellat'
                },
                {
                    'OccupationCatelogy_id  ': 'saepe',
                    OccupationGroup_id: 721,
                    name: 'temporibus'
                },
                {
                    'OccupationCatelogy_id  ': 'est',
                    OccupationGroup_id: 702,
                    name: 'omnis'
                },
                {
                    'OccupationCatelogy_id  ': 'natus',
                    OccupationGroup_id: 354,
                    name: 'repellat'
                },
                {
                    'OccupationCatelogy_id  ': 'dolorum',
                    OccupationGroup_id: 759,
                    name: 'laboriosam'
                },
                {
                    'OccupationCatelogy_id  ': 'est',
                    OccupationGroup_id: 272,
                    name: 'ut'
                },
                {
                    'OccupationCatelogy_id  ': 'quasi',
                    OccupationGroup_id: 725,
                    name: 'ab'
                },
                {
                    'OccupationCatelogy_id  ': 'et',
                    OccupationGroup_id: 594,
                    name: 'qui'
                },
                {
                    'OccupationCatelogy_id  ': 'ut',
                    OccupationGroup_id: 139,
                    name: 'facilis'
                },
                {
                    'OccupationCatelogy_id  ': 'nulla',
                    OccupationGroup_id: 899,
                    name: 'in'
                },
                {
                    'OccupationCatelogy_id  ': 'quia',
                    OccupationGroup_id: 960,
                    name: 'sapiente'
                },
                {
                    'OccupationCatelogy_id  ': 'iste',
                    OccupationGroup_id: 397,
                    name: 'quis'
                },
                {
                    'OccupationCatelogy_id  ': 'deserunt',
                    OccupationGroup_id: 414,
                    name: 'quo'
                },
                {
                    'OccupationCatelogy_id  ': 'laboriosam',
                    OccupationGroup_id: 133,
                    name: 'qui'
                },
                {
                    'OccupationCatelogy_id  ': 'esse',
                    OccupationGroup_id: 364,
                    name: 'vitae'
                },
                {
                    'OccupationCatelogy_id  ': 'qui',
                    OccupationGroup_id: 700,
                    name: 'unde'
                },
                {
                    'OccupationCatelogy_id  ': 'explicabo',
                    OccupationGroup_id: 20,
                    name: 'earum'
                },
                {
                    'OccupationCatelogy_id  ': 'magni',
                    OccupationGroup_id: 845,
                    name: 'provident'
                },
                {
                    'OccupationCatelogy_id  ': 'repellendus',
                    OccupationGroup_id: 663,
                    name: 'consequuntur'
                },
                {
                    'OccupationCatelogy_id  ': 'ut',
                    OccupationGroup_id: 875,
                    name: 'et'
                },
                {
                    'OccupationCatelogy_id  ': 'dolor',
                    OccupationGroup_id: 739,
                    name: 'voluptas'
                },
                {
                    'OccupationCatelogy_id  ': 'facere',
                    OccupationGroup_id: 102,
                    name: 'velit'
                },
                {
                    'OccupationCatelogy_id  ': 'aut',
                    OccupationGroup_id: 350,
                    name: 'ex'
                },
                {
                    'OccupationCatelogy_id  ': 'expedita',
                    OccupationGroup_id: 272,
                    name: 'est'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});