/*
 * File: app/store/positionModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.positionModels', {
    extend: 'Ext.data.Store',
    alias: 'store.positionmodels',

    requires: [
        'FrontHPApp.model.PositionModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'positionModels',
            model: 'FrontHPApp.model.PositionModel',
            data: [
                {
                    OccupationCareer_id: 388,
                    Position_id: 'reprehenderit',
                    name: 'officia'
                },
                {
                    OccupationCareer_id: 452,
                    Position_id: 'itaque',
                    name: 'placeat'
                },
                {
                    OccupationCareer_id: 482,
                    Position_id: 'molestiae',
                    name: 'non'
                },
                {
                    OccupationCareer_id: 142,
                    Position_id: 'molestiae',
                    name: 'accusantium'
                },
                {
                    OccupationCareer_id: 300,
                    Position_id: 'vero',
                    name: 'aut'
                },
                {
                    OccupationCareer_id: 559,
                    Position_id: 'itaque',
                    name: 'commodi'
                },
                {
                    OccupationCareer_id: 764,
                    Position_id: 'ipsa',
                    name: 'sit'
                },
                {
                    OccupationCareer_id: 515,
                    Position_id: 'expedita',
                    name: 'culpa'
                },
                {
                    OccupationCareer_id: 252,
                    Position_id: 'id',
                    name: 'qui'
                },
                {
                    OccupationCareer_id: 34,
                    Position_id: 'quod',
                    name: 'est'
                },
                {
                    OccupationCareer_id: 878,
                    Position_id: 'vel',
                    name: 'adipisci'
                },
                {
                    OccupationCareer_id: 762,
                    Position_id: 'quaerat',
                    name: 'doloribus'
                },
                {
                    OccupationCareer_id: 615,
                    Position_id: 'veritatis',
                    name: 'voluptatum'
                },
                {
                    OccupationCareer_id: 932,
                    Position_id: 'maxime',
                    name: 'et'
                },
                {
                    OccupationCareer_id: 393,
                    Position_id: 'suscipit',
                    name: 'atque'
                },
                {
                    OccupationCareer_id: 62,
                    Position_id: 'et',
                    name: 'dignissimos'
                },
                {
                    OccupationCareer_id: 384,
                    Position_id: 'dignissimos',
                    name: 'ea'
                },
                {
                    OccupationCareer_id: 723,
                    Position_id: 'qui',
                    name: 'possimus'
                },
                {
                    OccupationCareer_id: 675,
                    Position_id: 'voluptatem',
                    name: 'corrupti'
                },
                {
                    OccupationCareer_id: 101,
                    Position_id: 'ut',
                    name: 'consequatur'
                },
                {
                    OccupationCareer_id: 399,
                    Position_id: 'veniam',
                    name: 'numquam'
                },
                {
                    OccupationCareer_id: 544,
                    Position_id: 'impedit',
                    name: 'doloribus'
                },
                {
                    OccupationCareer_id: 162,
                    Position_id: 'animi',
                    name: 'libero'
                },
                {
                    OccupationCareer_id: 989,
                    Position_id: 'molestias',
                    name: 'aut'
                },
                {
                    OccupationCareer_id: 741,
                    Position_id: 'velit',
                    name: 'magni'
                },
                {
                    OccupationCareer_id: 304,
                    Position_id: 'id',
                    name: 'exercitationem'
                },
                {
                    OccupationCareer_id: 436,
                    Position_id: 'illum',
                    name: 'alias'
                },
                {
                    OccupationCareer_id: 676,
                    Position_id: 'voluptas',
                    name: 'illo'
                },
                {
                    OccupationCareer_id: 930,
                    Position_id: 'et',
                    name: 'labore'
                },
                {
                    OccupationCareer_id: 794,
                    Position_id: 'vitae',
                    name: 'qui'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});