using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Com.Ktbl.FontHP.Domain.Request
{
    public class RequestDomain
    {
        public virtual string RequestNo { get; set; }
        public virtual DateTime? RequestDate { get; set; }
        public virtual string Branch { get; set; }
        public virtual string Agrcode { get; set; }
        public virtual string CustomerCode { get; set; }
        public virtual string ThirdpartyCode { get; set; }
        public virtual string ThirdRecAmt { get; set; }
        public virtual string ComGroup { get; set; }
        public virtual string AO { get; set; }
        public virtual string VatBy { get; set; }
        public virtual string Checker { get; set; }
        public virtual string Creditor { get; set; }
        public virtual string LeadNo { get; set; }
        public virtual string Advisor { get; set; }
        public virtual string BranchAdvisor { get; set; }
        public virtual bool? AdvisorCom { get; set; }
        public virtual string RequestDoc { get; set; }
        public virtual DateTime? RequestDocfileDate { get; set; }
        public virtual DateTime? RequestDocfaxDate { get; set; }
        public virtual bool? FlagFax2file { get; set; }
        public virtual DateTime? InterestStartDate { get; set; }
        public virtual int? BeginTerm { get; set; }
        public virtual string Campaign { get; set; }
        public virtual string CarType { get; set; }
        public virtual string DownType { get; set; }
        public virtual string Priceofcar { get; set; }
        public virtual double? PricevatCar { get; set; }
        public virtual double? PriceCar { get; set; }
        public virtual double? VatCar { get; set; }
        public virtual double? DownPercent { get; set; }
        public virtual double? DownTotal { get; set; }
        public virtual double? DownCar { get; set; }
        public virtual double? DownVat { get; set; }
        public virtual int? Term { get; set; }
        public virtual string Termtype { get; set; }
        public virtual double? Cost { get; set; }
        public virtual double? CostVat { get; set; }
        public virtual string Typeinterest { get; set; }
        public virtual string Typeround { get; set; }
        public virtual double? FlatRate { get; set; }
        public virtual double? Benefit { get; set; }
        public virtual double? BenefitVat { get; set; }
        public virtual float? EffectiveRate { get; set; }
        public virtual float? IrrRate { get; set; }
        public virtual double? RentTotal { get; set; }
        public virtual double? RentVat { get; set; }
        public virtual double? TermAmount { get; set; }
        public virtual double? TermVat { get; set; }
        public virtual double? TermNet { get; set; }
        public virtual double? LastAmount { get; set; }
        public virtual double? LastVat { get; set; }
        public virtual double? LastNet { get; set; }
        public virtual string PayTermType { get; set; }
        public virtual string SubPayTermType { get; set; }
        public virtual DateTime? FirstDate { get; set; }
        public virtual DateTime? FirstDueDate { get; set; }
        public virtual DateTime? InvDate { get; set; }
        public virtual string InvNo { get; set; }
        public virtual DateTime? TransDate { get; set; }
        public virtual DateTime? LastDueDate { get; set; }
        public virtual string ConditionPayDown { get; set; }
        public virtual string Custpaysellman { get; set; }
        public virtual string Typeofconsumer { get; set; }
        public virtual string Conditionpayment { get; set; }
        public virtual string AccountNo { get; set; }
        public virtual string BankCode { get; set; }
        public virtual string ObjectLeasing { get; set; }
        public virtual string OthSpecial1 { get; set; }
        public virtual string OthSpecial2 { get; set; }
        public virtual string Marriage { get; set; }
        public virtual string SpouseNameEng { get; set; }
        public virtual string SpouseNameThai { get; set; }
        public virtual string SpouseCompany { get; set; }
        public virtual string SpousePosition { get; set; }
        public virtual string SpouseTelephone { get; set; }
        public virtual double? AssetAmount { get; set; }
        public virtual int? EmployeeQty { get; set; }
        public virtual string CustomerPosition { get; set; }
        public virtual double? Incomepermonth { get; set; }
        public virtual double? Debts { get; set; }
        public virtual double? RateDebtincome { get; set; }
        public virtual string Oth1 { get; set; }
        public virtual string Oth2 { get; set; }
        public virtual string Oth3 { get; set; }
        public virtual string ApproveSpecial { get; set; }
        public virtual string Othspecial { get; set; }
        public virtual string ConditionSpecial { get; set; }
        public virtual string AssetNo { get; set; }
        public virtual string ShowRoom { get; set; }
        public virtual string ComRateAbsorb { get; set; }
        public virtual double? ComRateHiring { get; set; }
        public virtual double? ComRateIns { get; set; }
        public virtual double? SubidynetFlatRate { get; set; }
        public virtual double? SubidyflatRateCust { get; set; }
        public virtual string PayDeduction { get; set; }
        public virtual double? NetPreminumAmount { get; set; }
        public virtual double? DeductBaseAmount { get; set; }
        public virtual double? WithholdingTaxAmt { get; set; }
        public virtual double? SubsidyAmt { get; set; }
        public virtual double? SubsidyVatAmt { get; set; }
        public virtual double? SubsidynetpaidAmt { get; set; }
        public virtual string ReqStatus { get; set; }
        public virtual string ReqReason { get; set; }
        public virtual bool? FlagBlacklist { get; set; }
        public virtual bool? FlagCreditscoring { get; set; }
        public virtual string Guaruntor1 { get; set; }
        public virtual string Relation1 { get; set; }
        public virtual double? Income1 { get; set; }
        public virtual double? Debt1 { get; set; }
        public virtual string Guaruntor2 { get; set; }
        public virtual string Relation2 { get; set; }
        public virtual double? Income2 { get; set; }
        public virtual double? Debt2 { get; set; }
        public virtual string Guaruntor3 { get; set; }
        public virtual string Relation3 { get; set; }
        public virtual double? Income3 { get; set; }
        public virtual double? Debt3 { get; set; }
        public virtual string Guaruntor4 { get; set; }
        public virtual string Relation4 { get; set; }
        public virtual double? Income4 { get; set; }
        public virtual double? Debt4 { get; set; }
        public virtual bool? Posted { get; set; }
        public virtual bool? Pending { get; set; }
        public virtual string PendingBy { get; set; }
        public virtual DateTime? PendingDate { get; set; }
        public virtual bool? Approved { get; set; }
        public virtual string ApproveBy { get; set; }
        public virtual DateTime? ApproveDate { get; set; }
        public virtual string ApproveByMkt { get; set; }
        public virtual bool? FlagPolymath { get; set; }
        public virtual DateTime? TermDateRequest { get; set; }
        public virtual bool? FlagRecept { get; set; }
        public virtual bool? FlagPo { get; set; }
        public virtual DateTime? PaidCommDate { get; set; }
        public virtual DateTime? ComDate { get; set; }
        public virtual string ScoringNo { get; set; }
        public virtual string LevelApprove { get; set; }
        public virtual DateTime? CreateDate { get; set; }
        public virtual string CreateUser { get; set; }
        public virtual DateTime? ModifyDate { get; set; }
        public virtual string ModifyUser { get; set; }
        public virtual bool? Active { get; set; }
        public virtual DateTime? LeadCreateDate { get; set; }
        public virtual string LeadCreateUser { get; set; }
        public virtual string CustomerCode2 { get; set; }
        public virtual string CustomerPosition2 { get; set; }
        public virtual double? Incomepermonth2 { get; set; }
        public virtual double? Debts2 { get; set; }
        public virtual double? RateDebtincome2 { get; set; }
        public virtual string ScoringNo2 { get; set; }
        public virtual string ApproveLevel { get; set; }
        public virtual string CampaignintCode { get; set; }
        public virtual string CampaignsubCode { get; set; }
        public virtual double? SubsidyAmt2 { get; set; }
        public virtual double? SubsidyVatAmt2 { get; set; }
        public virtual string PromotionEventCode { get; set; }
        public virtual bool? FlagPost { get; set; }
        public virtual DateTime? Unpost { get; set; }
        public virtual string Unpostby { get; set; }
        public virtual bool? Ktbsalary { get; set; }
        public virtual string HoldType { get; set; }
        public virtual string Cat3 { get; set; }
        public virtual string NreqStatus { get; set; }
        public virtual string CrRemark { get; set; }
        public virtual int? ScoringSeq { get; set; }
        public virtual bool? FlagLoan { get; set; }
        public virtual bool? Loanprtc { get; set; }
        public virtual string ComInvRef { get; set; }
        public virtual DateTime? ComInvDate { get; set; }
        public virtual int? ComTermHiring { get; set; }
        public virtual bool? Topuploan { get; set; }
        public virtual double? DebsIns { get; set; }
        public virtual bool? DebsInsFlag { get; set; }
        public virtual double? DebsAgr { get; set; }
        public virtual bool? DebsAgrFlag { get; set; }
        public virtual bool? DebsCompolFlag { get; set; }
        public virtual string Ddtypereg { get; set; }
        public virtual bool? Loanproctectionchq { get; set; }
        public virtual double? DebCarforcash { get; set; }
        public virtual string DebCarforcashRef { get; set; }
        public virtual double? HiringIncamountvat { get; set; }
        public virtual double? SubFinAmt { get; set; }
        public virtual string InsComAbsorb { get; set; }
        public virtual double? HiringChargincvat { get; set; }
        public virtual double? ComRateInsvat { get; set; }
        public virtual double? SubsidyWh { get; set; }
        public virtual double? ComRateVat { get; set; }
        public virtual double? SubsidyNetpaid { get; set; }
        public virtual double? SubHpAmt { get; set; }
        public virtual string InsComPayto { get; set; }
        public virtual double? HiringNet { get; set; }
        public virtual double? HiringAmountvat { get; set; }
        public virtual double? ComInsWh { get; set; }
        public virtual string ProductType { get; set; }
        public virtual double? ComInsNetpaid { get; set; }
        public virtual string ComHiringPayto { get; set; }
        public virtual double? HiringWh { get; set; }
        public virtual int? ComMaxTerm { get; set; }
        public virtual double? ComMaxRate { get; set; }
        public virtual int? ComTermHirring { get; set; }
        public virtual bool? Alertbooking { get; set; }
        public virtual bool? FlagWeb { get; set; }
        public virtual string Mktcde { get; set; }
        public virtual DateTime? AgrStartDd { get; set; }
        public virtual bool? FlagCommHirr { get; set; }
        public virtual int? Ages { get; set; }
        public virtual DateTime? TransComsaleDd { get; set; }
        public virtual string Nagrcode { get; set; }
        public virtual string Opergroup { get; set; }
        public virtual double? Balloonamt { get; set; }
        public virtual bool? Dealertocustomer { get; set; }
        public virtual int? DueDay { get; set; }
        public virtual double? EffYield { get; set; }
        public virtual DateTime? PaidDate { get; set; }
        public virtual double? Unearn { get; set; }
    }
}
