/*
 * File: app/view/main/home/Indox.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.home.Indox', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainhomeindox',

    requires: [
        'FrontHPApp.view.main.home.IndoxViewModel',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'mainhomeindox'
    },
    layout: 'border',
    title: 'Inbox',

    dockedItems: [
        {
            xtype: 'panel',
            dock: 'top',
            bodyPadding: 50,
            title: 'ตัวอย่าง กราฟ',
            items: [
                {
                    xtype: 'cartesian',
                    minHeight: 350,
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    bind: {
                        store: '{jobIndexes}'
                    },
                    axes: [
                        {
                            type: 'category',
                            fields: [
                                'Name'
                            ],
                            position: 'bottom'
                        },
                        {
                            type: 'numeric',
                            fields: [
                                'Success',
                                'Inprogress',
                                'failure'
                            ],
                            grid: {
                                odd: {
                                    fill: '#e8e8e8'
                                }
                            },
                            position: 'left'
                        }
                    ],
                    series: [
                        {
                            type: 'bar',
                            title: [
                                'Chart'
                            ],
                            xField: 'Name',
                            yField: [
                                'Success',
                                'Inprogress',
                                'failure'
                            ]
                        }
                    ],
                    interactions: [
                        {
                            type: 'panzoom'
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            region: 'center',
            title: 'ภาพรวมของงานทั้งหมด',
            bind: {
                store: '{jobIndexes}'
            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Name',
                    text: 'Name',
                    flex: -1
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'Success',
                    text: 'Success',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'Inprogress',
                    text: 'Inprogress',
                    format: '00'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'failure',
                    text: 'Fail',
                    format: '00'
                }
            ]
        }
    ]

});