/*
 * File: app/view/main/home/IndoxViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.home.IndoxViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.mainhomeindox',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        jobIndexes: {
            model: 'FrontHPApp.model.JobIndex',
            data: [
                {
                    id: 1,
                    Name: 'thawat1',
                    Success: 50,
                    Inprogress: 25,
                    failure: 25
                },
                {
                    id: 2,
                    Name: 'thawat265',
                    Success: 10,
                    Inprogress: 70,
                    failure: 20
                },
                {
                    id: 3,
                    Name: 'thawat521',
                    Success: 25,
                    Inprogress: 25,
                    failure: 50
                },
                {
                    id: 4,
                    Name: 'thawat789',
                    Success: 33,
                    Inprogress: 37,
                    failure: 30
                },
                {
                    id: 5,
                    Name: 'thawat2',
                    Success: 38,
                    Inprogress: 32,
                    failure: 30
                },
                {
                    id: 6,
                    Name: 'thawat22',
                    Success: 70,
                    Inprogress: 10,
                    failure: 20
                },
                {
                    id: 7,
                    Name: 'thawat3',
                    Success: 30,
                    Inprogress: 50,
                    failure: 20
                },
                {
                    id: 8,
                    Name: 'thawat4',
                    Success: 76,
                    Inprogress: 4,
                    failure: 20
                },
                {
                    id: 9,
                    Name: 'thawat6',
                    Success: 16,
                    Inprogress: 30,
                    failure: 54
                },
                {
                    id: 10,
                    Name: 'thawat7',
                    Success: 16,
                    Inprogress: 44,
                    failure: 40
                },
                {
                    id: 11,
                    Name: 'thawat8',
                    Success: 26,
                    Inprogress: 34,
                    failure: 40
                },
                {
                    id: 12,
                    Name: 'thawat5',
                    Success: 36,
                    Inprogress: 54,
                    failure: 10
                },
                {
                    id: 12,
                    Name: 'thawat12',
                    Success: 46,
                    Inprogress: 24,
                    failure: 30
                },
                
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});