/*
 * File: app/store/BranchStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.BranchStore', {
    extend: 'Ext.data.Store',
    alias: 'store.branchstore',

    requires: [
        'FrontHPApp.model.BranchModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'BranchStore',
            model: 'FrontHPApp.model.BranchModel',
            data: [
                {
                    Id: 162,
                    Name: 'ullam'
                },
                {
                    Id: 271,
                    Name: 'sint'
                },
                {
                    Id: 747,
                    Name: 'delectus'
                },
                {
                    Id: 826,
                    Name: 'placeat'
                },
                {
                    Id: 762,
                    Name: 'beatae'
                },
                {
                    Id: 78,
                    Name: 'et'
                },
                {
                    Id: 296,
                    Name: 'consequatur'
                },
                {
                    Id: 313,
                    Name: 'rerum'
                },
                {
                    Id: 918,
                    Name: 'aut'
                },
                {
                    Id: 469,
                    Name: 'repellendus'
                },
                {
                    Id: 19,
                    Name: 'in'
                },
                {
                    Id: 669,
                    Name: 'aut'
                },
                {
                    Id: 764,
                    Name: 'veniam'
                },
                {
                    Id: 566,
                    Name: 'tempora'
                },
                {
                    Id: 325,
                    Name: 'numquam'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});