/*
 * File: app/store/comHirModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.comHirModels', {
    extend: 'Ext.data.Store',
    alias: 'store.comhirmodels',

    requires: [
        'FrontHPApp.model.ComHirModel',
        'Ext.data.proxy.Memory'
    ],
    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'comhirmodels',
            model: 'FrontHPApp.model.ComHirModel',
            autoLoad: true,
            proxy: {
                type: 'rest',
                url: 'api/ComHiring/getcomhiringLoad',
                reader: {
                    type: 'json',
                    rootProperty: 'items'
                },
                api: {
                    destroy: 'api/ComHiring'
                }
            }
        }, cfg)]);
    }
   
});