/*
 * File: app/store/commitinSpecialModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.commitinSpecialModels', {
    extend: 'Ext.data.Store',
    alias: 'store.commitinspecialmodels',

    requires: [
        'FrontHPApp.model.CommitinSpecialModel',
        'Ext.data.proxy.Memory'
    ],

    //add by p2p 20180908
    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'commitinspecialmodels',
            model: 'FrontHPApp.model.CommitinSpecialModel',
            autoLoad: true,
            proxy: {
                type: 'rest',
                url: 'api/ComSpacial/getcomspacialload',
                reader: {
                    type: 'json',
                    rootProperty: 'items'
                },
                api: {
                    destroy: 'api/ComSpacial'
                }
            }
        }, cfg)]);
    }
});