/*
 * File: app/store/historyCheckDocumentModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.historyCheckDocumentModels', {
    extend: 'Ext.data.Store',
    alias: 'store.historycheckdocumentmodels',

    requires: [
        'FrontHPApp.model.HistoryCheckDocumentModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'historyCheckDocumentModels',
            model: 'FrontHPApp.model.HistoryCheckDocumentModel',
            data: [
                {
                    RequestNo: 550,
                    RequestDate: '5/16/2007',
                    CitizenId: 449,
                    CusName: 'inventore',
                    NCBStatus: 'quasi',
                    RequestStatus: 'ut'
                },
                {
                    RequestNo: 509,
                    RequestDate: '6/2/2004',
                    CitizenId: 76,
                    CusName: 'sit',
                    NCBStatus: 'voluptatem',
                    RequestStatus: 'occaecati'
                },
                {
                    RequestNo: 259,
                    RequestDate: '4/19/2011',
                    CitizenId: 735,
                    CusName: 'rem',
                    NCBStatus: 'expedita',
                    RequestStatus: 'exercitationem'
                },
                {
                    RequestNo: 100,
                    RequestDate: '7/11/2014',
                    CitizenId: 437,
                    CusName: 'harum',
                    NCBStatus: 'officia',
                    RequestStatus: 'totam'
                },
                {
                    RequestNo: 110,
                    RequestDate: '7/9/2002',
                    CitizenId: 298,
                    CusName: 'quibusdam',
                    NCBStatus: 'voluptatibus',
                    RequestStatus: 'labore'
                },
                {
                    RequestNo: 517,
                    RequestDate: '12/4/2010',
                    CitizenId: 247,
                    CusName: 'dicta',
                    NCBStatus: 'pariatur',
                    RequestStatus: 'voluptas'
                },
                {
                    RequestNo: 622,
                    RequestDate: '5/16/2006',
                    CitizenId: 466,
                    CusName: 'sed',
                    NCBStatus: 'sunt',
                    RequestStatus: 'eum'
                },
                {
                    RequestNo: 816,
                    RequestDate: '10/13/2001',
                    CitizenId: 420,
                    CusName: 'corrupti',
                    NCBStatus: 'soluta',
                    RequestStatus: 'eius'
                },
                {
                    RequestNo: 613,
                    RequestDate: '7/19/2014',
                    CitizenId: 311,
                    CusName: 'omnis',
                    NCBStatus: 'voluptatem',
                    RequestStatus: 'sunt'
                },
                {
                    RequestNo: 370,
                    RequestDate: '6/5/2009',
                    CitizenId: 577,
                    CusName: 'quo',
                    NCBStatus: 'quidem',
                    RequestStatus: 'neque'
                },
                {
                    RequestNo: 765,
                    RequestDate: '7/4/2004',
                    CitizenId: 157,
                    CusName: 'incidunt',
                    NCBStatus: 'illum',
                    RequestStatus: 'voluptas'
                },
                {
                    RequestNo: 929,
                    RequestDate: '12/17/2006',
                    CitizenId: 101,
                    CusName: 'omnis',
                    NCBStatus: 'vel',
                    RequestStatus: 'ratione'
                },
                {
                    RequestNo: 832,
                    RequestDate: '7/11/2006',
                    CitizenId: 131,
                    CusName: 'velit',
                    NCBStatus: 'facilis',
                    RequestStatus: 'facere'
                },
                {
                    RequestNo: 868,
                    RequestDate: '1/22/2002',
                    CitizenId: 285,
                    CusName: 'qui',
                    NCBStatus: 'aut',
                    RequestStatus: 'consequuntur'
                },
                {
                    RequestNo: 813,
                    RequestDate: '3/5/2009',
                    CitizenId: 301,
                    CusName: 'sit',
                    NCBStatus: 'ut',
                    RequestStatus: 'quia'
                },
                {
                    RequestNo: 620,
                    RequestDate: '2/14/2003',
                    CitizenId: 578,
                    CusName: 'sed',
                    NCBStatus: 'temporibus',
                    RequestStatus: 'nam'
                },
                {
                    RequestNo: 840,
                    RequestDate: '1/10/2006',
                    CitizenId: 788,
                    CusName: 'adipisci',
                    NCBStatus: 'corporis',
                    RequestStatus: 'est'
                },
                {
                    RequestNo: 186,
                    RequestDate: '9/10/2013',
                    CitizenId: 67,
                    CusName: 'blanditiis',
                    NCBStatus: 'nulla',
                    RequestStatus: 'consequuntur'
                },
                {
                    RequestNo: 251,
                    RequestDate: '12/16/2001',
                    CitizenId: 513,
                    CusName: 'quae',
                    NCBStatus: 'ea',
                    RequestStatus: 'quis'
                },
                {
                    RequestNo: 798,
                    RequestDate: '9/13/2007',
                    CitizenId: 781,
                    CusName: 'cum',
                    NCBStatus: 'maxime',
                    RequestStatus: 'quam'
                },
                {
                    RequestNo: 518,
                    RequestDate: '10/5/2003',
                    CitizenId: 415,
                    CusName: 'quia',
                    NCBStatus: 'adipisci',
                    RequestStatus: 'laborum'
                },
                {
                    RequestNo: 581,
                    RequestDate: '6/23/2010',
                    CitizenId: 778,
                    CusName: 'ratione',
                    NCBStatus: 'delectus',
                    RequestStatus: 'hic'
                },
                {
                    RequestNo: 674,
                    RequestDate: '11/10/2001',
                    CitizenId: 522,
                    CusName: 'possimus',
                    NCBStatus: 'culpa',
                    RequestStatus: 'officiis'
                },
                {
                    RequestNo: 209,
                    RequestDate: '4/9/2004',
                    CitizenId: 866,
                    CusName: 'at',
                    NCBStatus: 'illo',
                    RequestStatus: 'omnis'
                },
                {
                    RequestNo: 84,
                    RequestDate: '1/2/2009',
                    CitizenId: 701,
                    CusName: 'nisi',
                    NCBStatus: 'praesentium',
                    RequestStatus: 'hic'
                },
                {
                    RequestNo: 334,
                    RequestDate: '5/17/2014',
                    CitizenId: 50,
                    CusName: 'at',
                    NCBStatus: 'recusandae',
                    RequestStatus: 'quae'
                },
                {
                    RequestNo: 49,
                    RequestDate: '10/11/2004',
                    CitizenId: 347,
                    CusName: 'placeat',
                    NCBStatus: 'magni',
                    RequestStatus: 'fugit'
                },
                {
                    RequestNo: 956,
                    RequestDate: '6/5/2009',
                    CitizenId: 313,
                    CusName: 'accusantium',
                    NCBStatus: 'hic',
                    RequestStatus: 'autem'
                },
                {
                    RequestNo: 229,
                    RequestDate: '6/7/2008',
                    CitizenId: 864,
                    CusName: 'harum',
                    NCBStatus: 'omnis',
                    RequestStatus: 'voluptatibus'
                },
                {
                    RequestNo: 989,
                    RequestDate: '6/5/2001',
                    CitizenId: 513,
                    CusName: 'minima',
                    NCBStatus: 'enim',
                    RequestStatus: 'voluptatem'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});