/*
 * File: app/store/sunsidyModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.sunsidyModels', {
    extend: 'Ext.data.Store',
    alias: 'store.sunsidymodels',

    requires: [
        'FrontHPApp.model.SunsidyModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'sunsidyModels',
            model: 'FrontHPApp.model.SunsidyModel',
            data: [
                {
                    id: 61,
                    List: 'non',
                    Detail: 'cumque',
                    Amount: 983.49
                },
                {
                    id: 203,
                    List: 'sint',
                    Detail: 'fugiat',
                    Amount: 155.19
                },
                {
                    id: 243,
                    List: 'totam',
                    Detail: 'aspernatur',
                    Amount: 625.21
                },
                {
                    id: 699,
                    List: 'excepturi',
                    Detail: 'culpa',
                    Amount: 846
                },
                {
                    id: 897,
                    List: 'nostrum',
                    Detail: 'eos',
                    Amount: 357.3
                },
                {
                    id: 593,
                    List: 'non',
                    Detail: 'possimus',
                    Amount: 929.36
                },
                {
                    id: 635,
                    List: 'veritatis',
                    Detail: 'repellendus',
                    Amount: 852.77
                },
                {
                    id: 728,
                    List: 'inventore',
                    Detail: 'autem',
                    Amount: 67.54
                },
                {
                    id: 657,
                    List: 'est',
                    Detail: 'et',
                    Amount: 249.31
                },
                {
                    id: 241,
                    List: 'voluptate',
                    Detail: 'doloribus',
                    Amount: 115.26
                },
                {
                    id: 564,
                    List: 'rerum',
                    Detail: 'omnis',
                    Amount: 606.51
                },
                {
                    id: 736,
                    List: 'enim',
                    Detail: 'illum',
                    Amount: 857.01
                },
                {
                    id: 784,
                    List: 'numquam',
                    Detail: 'cum',
                    Amount: 555.01
                },
                {
                    id: 260,
                    List: 'et',
                    Detail: 'voluptatibus',
                    Amount: 457.82
                },
                {
                    id: 130,
                    List: 'eligendi',
                    Detail: 'dolor',
                    Amount: 447.14
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});