/*
 * File: app/store/typeCustomerModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.typeCustomerModels', {
    extend: 'Ext.data.Store',
    alias: 'store.typecustomermodels',

    requires: [
        'FrontHPApp.model.TypeCustomerModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'typeCustomerModels',
            model: 'FrontHPApp.model.TypeCustomerModel',
            data: [
                {
                    id: 100,
                    name: 'ratione',
                    flg: 'et'
                },
                {
                    id: 495,
                    name: 'sunt',
                    flg: 'architecto'
                },
                {
                    id: 930,
                    name: 'veritatis',
                    flg: 'sit'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});