/*
 * File: app/view/FrmGarantorViewController3.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.FrmGarantorViewController3', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainmainmarketingwindowsubsidywindow',

    control: {
        "#mygridpanel2": {
            select: 'onGridpanelSelect',
            deselect: 'onMygridpanel2Deselect',
            cellclick: 'onMygridpanel2CellClick',
            edit: 'onMygridpanel2Edit',
            validate: 'onMygridpanel2Validate'
        }
    },

    onGridpanelSelect: function(rowmodel, record, index, eOpts) {

    },

    onMygridpanel2Deselect: function(rowmodel, record, index, eOpts) {

    },

    onMygridpanel2CellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

    },

    onMygridpanel2Edit: function() {

    },

    onMygridpanel2Validate: function() {

    },

    onAddClick: function(button, e, eOpts) {

    },

    onEditClick: function(button, e, eOpts) {

    },

    onDeleteClick: function(button, e, eOpts) {
        var view = this.getView(),
            GridGarantor = view.down("#GridSubsidy"), //itemid
            store = GridGarantor.getStore(),
            selectRecord = GridGarantor.getSelection(),
            CheckCountSelect = selectRecord.length;

        if (CheckCountSelect > 0)
        {
            Ext.MessageBox.confirm("Confirm","คุณต้องการที่จะลบรายการใช่หรือไม่?",function(btn){

                if(btn == 'yes'){

                    for(i=0;i<CheckCountSelect;i++){

                        store.remove(selectRecord[i]);

                    }
                }

            },this);

        }
        else
        {

        }
    }

});
