/*
 * File: app/view/main/mainmarketing/MarketingTab.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.MarketingTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainmainmarketingmarketingtab',

    requires: [
        'FrontHPApp.view.main.mainmarketing.MarketingTabViewModel',
        'FrontHPApp.view.main.mainmarketing.MarketingTabViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.XTemplate',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.toolbar.Paging'
    ],

    controller: 'mainmainmarketingmarketingtab',
    viewModel: {
        type: 'mainmainmarketingmarketingtab'
    },
    minHeight: 600,
    layout: 'border',
    manageHeight: false,

    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            bodyPadding: 10,
            iconCls: 'icon-details',
            manageHeight: false,
            title: 'ค้นหาข้อมูล',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    width: 800,
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 150
                    },
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'วันที่ใบคำข้อจาก',
                            labelClsExtra: '',
                            labelStyle: '',
                            name: 'StartDate',
                            allowBlank: false,
                            emptyText: '[วว/ดด/ปปปป]',
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'ถึงวันที่ใบคำขอ',
                            name: 'Enddate',
                            allowBlank: false,
                            emptyText: '[วว/ดด/ปปปป]',
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'เลขที่ใบคำขอ',
                            emptyText: '[เลขที่ใบคำขอ]',
                            name: 'RequestNo',
                            hideTrigger: true
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'สถานะใบคำขอ',
                            name: 'StatusRequest',
                            emptyText: '[เลือก]',
                            autoLoadOnValue: true,
                            displayField: 'Name',
                            store: 'combo.RequestStatusStore',
                            valueField: 'id',
                            width: 390,
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'เลขที่ประชาชน',
                            emptyText: '[เลขที่บัตรประชาชน]',
                            name: 'CitizenID',
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'ชื่อ-นามสกุลผู้เช่าซื้อ',
                            emptyText: '[ชื่อ-นามสกุลผู้เช่าซื้อ]',
                            width: 390,
                            name: 'Cusname',
                        },
                        {
                            xtype: 'combobox',
                            colspan: 2,
                            fieldLabel: 'สาขา',
                            emptyText: '[สาขา]',
                            autoLoadOnValue: true,
                            displayField: 'Name',
                            store: 'combo.BranchStore',
                            name: 'Branch',
                            valueField: 'id'
                        },
                        {
                            xtype: 'container',
                            colspan: 2,
                            width: 800,
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '0 5 5 0',
                                    ui: 'default-small',
                                    iconCls: 'icon-find',
                                    text: 'ค้นหาข้อมูล',
                                    listeners: {
                                        click: 'onFindRequestNOClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    ui: 'default-small',
                                    iconCls: 'icon-reset',
                                    text: 'เคลียร์',
                                    listeners: {
                                        click: 'onClearGridClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            iconCls: 'icon-details',
            title: 'ข้อมูลเลขที่ใบคำขอ',
            store: 'requestModels',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-add',
                            text: 'เพิ่ม',
                            listeners: {
                                click: 'onAddClick'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-details',
                            text: 'ViewDetail',
                            listeners: {
                                click: 'onViewDetailClick'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-edit',
                            text: 'Cancel Flag',
                            listeners: {
                                click: 'onCancelFlgClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'requestModels'
                }
            ],
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 45,
                    align: 'center',
                    text: '#',
                    tooltip: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'RequestNo',
                    text: 'เลขที่ใบคำขอ'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.Date.format(value, 'd/m/Y');
                    },
                    dataIndex: 'RequestDate',
                    text: 'วันที่ใบคำขอ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CitizenId',
                    text: 'เลขที่บัตรประชาชน'
                },
                {
                    xtype: 'gridcolumn',
                    width: 141,
                    dataIndex: 'CusName',
                    text: 'ชื่อ - นามสกุลผู้เช่าซื้อ',
                    flex: -1
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        metaData.tdAttr = 'data-qtip="' + value + '"';
                        // Pass the call to the date column default renderer
                        return value;
                    },
                    width: 141,
                    dataIndex: 'DealerName',
                    text: 'ชื่อ Dealer'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'เอกสาร',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var accept = 'resources/icons/accept.gif',
                                    not_accept = 'resources/icons/cross.gif';

                                if(!value)
                                { //change the resource below :
                                    return '<img src="'+accept+'" />';
                                }else{
                                    return '<img src="'+not_accept+'" />';
                                }
                            },
                            width: 50,
                            dataIndex: 'doc1',
                            text: 'Doc1'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var accept = 'resources/icons/accept.gif',
                                    not_accept = 'resources/icons/cross.gif';

                                if(!value)
                                { //change the resource below :
                                    return '<img src="'+accept+'" />';
                                }else{
                                    return '<img src="'+not_accept+'" />';
                                }
                            },
                            width: 50,
                            dataIndex: 'doc2',
                            text: 'Doc2'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var accept = 'resources/icons/accept.gif',
                                    not_accept = 'resources/icons/cross.gif';

                                if(!value)
                                { //change the resource below :
                                    return '<img src="'+accept+'" />';
                                }else{
                                    return '<img src="'+not_accept+'" />';
                                }
                            },
                            width: 50,
                            dataIndex: 'doc3',
                            text: 'Doc3'
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    text: '#'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    text: ''
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var accept = 'resources/icons/accept.gif',
                            not_accept = 'resources/icons/cross.gif';

                        if(!value)
                        { //change the resource below :
                            return '<img src="'+accept+'" />';
                        }else{
                            return '<img src="'+not_accept+'" />';
                        }
                    },
                    width: 50,
                    dataIndex: 'Return',
                    text: 'ส่งคืน'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var accept = 'resources/icons/accept.gif',
                            not_accept = 'resources/icons/cross.gif';

                        if(!value)
                        { //change the resource below :
                            return '<img src="'+accept+'" />';
                        }else{
                            return '<img src="'+not_accept+'" />';
                        }
                    },
                    width: 50,
                    dataIndex: 'Loan',
                    text: 'Loan'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var accept = 'resources/icons/accept.gif',
                            not_accept = 'resources/icons/cross.gif';

                        if(!value)
                        { //change the resource below :
                            return '<img src="'+accept+'" />';
                        }else{
                            return '<img src="'+not_accept+'" />';
                        }
                    },
                    width: 50,
                    dataIndex: 'GurantorName',
                    text: 'ผู้ค้ำ',
                    hidden: true,
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'NCBStatus',
                    text: 'สถานะ NCB'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'RequestStatus',
                    text: 'สถานะใบคำขอ'
                }
            ],
            listeners: {
                itemdblclick: 'onDetaillItemDblClick'
            }
        }
    ]

});