/*
 * File: app/view/MyGridPanel1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.MyGridPanel1', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mygridpanel1',

    requires: [
        'FrontHPApp.view.MyGridPanel1ViewModel',
        'Ext.button.Button',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'mygridpanel1'
    },
    scrollable: true,
    collapsible: false,
    title: 'เอกสารแนบ',
    store: 'browsePaperMyModels',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    text: 'เพิ่ม'
                },
                {
                    xtype: 'button',
                    text: 'แก้ไข'
                },
                {
                    xtype: 'button',
                    text: 'ลบ'
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true
        }
    ],
    viewConfig: {
        height: 389,
        width: ''
    },
    columns: [
        {
            xtype: 'rownumberer',
            width: 45,
            text: 'Row'
        },
        {
            xtype: 'gridcolumn',
            width: '',
            dataIndex: 'IDNum',
            text: 'รหัส'
        },
        {
            xtype: 'gridcolumn',
            width: '',
            dataIndex: 'TypePaper',
            text: 'ประเภทเอกสาร'
        },
        {
            xtype: 'gridcolumn',
            width: 120,
            dataIndex: 'Order',
            text: 'ลำดับ'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'FileName',
            text: 'เอกสารแนบ'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Date',
            text: 'วันที่บันทึก'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Remark',
            text: 'หมายเหตุ'
        }
    ]

});