/*
 * File: app/view/Tab2/window/FrmBrowseFileCheck.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.Tab2.window.FrmBrowseFileCheck', {
    extend: 'Ext.window.Window',
    alias: 'widget.tab2windowfrmbrowsefilecheck',

    requires: [
        'FrontHPApp.view.Tab2.window.FrmBrowseFileCheckViewModel',
        'FrontHPApp.view.Tab2.window.FrmBrowseFileCheckViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.File',
        'Ext.form.field.TextArea',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel'
    ],

    controller: 'tab2windowfrmbrowsefilecheck',
    viewModel: {
        type: 'tab2windowfrmbrowsefilecheck'
    },
    autoShow: true,
    height: 600,
    itemId: 'panelbrowsefile',
    width: 700,
    layout: 'border',
    iconCls: 'icon-details',
    title: 'เอกสาร',

    items: [
        {
            xtype: 'form',
            region: 'north',
            reference: 'form',
            itemId: 'formBrowseFile',
            layout: 'auto',
            title: '',
            items: [
                {
                    xtype: 'container',
                    width: 650,
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 175,
                        width: '85%'
                    },
                    layout: {
                        type: 'table',
                        columns: 1
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '5 0 5 0',
                            fieldLabel: 'เลขที่ใบคำขอ',
                            labelAlign: 'right',
                            name: 'IDNum',
                            emptyText: '[เลขที่ใบคำขอ]'
                        },
                        {
                            xtype: 'combobox',
                            margin: '5 0 5 0',
                            fieldLabel: 'ประเภทเอกสาร',
                            labelAlign: 'right',
                            emptyText: '[ประเภทเอกสาร]',
                            displayField: 'name',
                            store: 'typePaperModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'filefield',
                            fieldLabel: 'เอกสาร',
                            labelAlign: 'right',
                            name: 'FileName',
                            emptyText: '[เอกสาร]'
                        },
                        {
                            xtype: 'textareafield',
                            fieldLabel: 'หมายเหตุ',
                            labelAlign: 'right',
                            name: 'Remark',
                            emptyText: '[หมายเหตุ]'
                        },
                        {
                            xtype: 'container',
                            colspan: 2,
                            height: 35,
                            width: 620,
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '0 5 0 5',
                                    iconCls: 'icon-paper',
                                    text: 'แนบเอกสาร',
                                    listeners: {
                                        click: 'onInsertPaperClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margins: '',
                                    margin: '0 5 0 5',
                                    iconCls: 'icon-reset',
                                    text: 'เคลียร์',
                                    listeners: {
                                        click: 'onClearClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            region: 'center',
            scrollable: true,
            collapsible: false,
            iconCls: 'icon-details',
            title: 'เอกสารแนบ',
            store: 'browsePaperMyModels',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            hidden: true,
                            ui: 'default-small',
                            iconCls: 'icon-add',
                            text: 'เพิ่ม',
                            listeners: {
                                click: 'onSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-edit',
                            text: 'แก้ไข',
                            listeners: {
                                click: 'onEditClick'
                            }
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-delete',
                            text: 'ลบ',
                            listeners: {
                                click: 'onDeleteClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ],
            viewConfig: {
                width: ''
            },
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 45,
                    align: 'center',
                    text: '#',
                    tooltip: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    width: '',
                    dataIndex: 'IDNum',
                    text: 'รหัส'
                },
                {
                    xtype: 'gridcolumn',
                    width: '',
                    dataIndex: 'TypePaper',
                    text: 'ประเภทเอกสาร'
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'Order',
                    text: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'FileName',
                    text: 'เอกสารแนบ',
                    flex: -1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Date',
                    text: 'วันที่บันทึก'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Remark',
                    text: 'หมายเหตุ'
                }
            ],
            listeners: {
                selectionchange: 'onGridBrowseFileSelectionChange'
            },
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ]

});