/*
 * File: app/model/AddressCusModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.model.ComHiringFormModel', {
    extend: 'Ext.data.Model',
    alias: 'model.comhiringformmodel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'float',
            name: 'WHTaxCorporation'
        },
        {
            type: 'float',
            name: 'WHTaxIndividual'
        },
        {
            type: 'float',
            name: 'MaximumCommission'
        },
        {
            type: 'float',
            name: 'DeductionRate'
        },
        {
            name: 'EntCodeShow'
        },
        {
            name: 'EntNameShow'
        },
        {
            type: 'float',
            name: 'HiringChargeIncludeVAT'
        },
        {
           
            name: 'PayCommissionTo'
        },
        {
            type: 'float',
            name: 'AmountVAT'
        },
        {
            type: 'float',
            name: 'DeductionRate'
        },
        {
            type: 'string',
            name: 'AbsorbTax'
        },
        {
            type: 'float',
            name: 'AmountIncludeVAT'
        },
        {
            type: 'float',
            name: 'DeductionRate'
        },
        {
            type: 'float',
            name: 'CommissionRate'
        },
        {
            type: 'float',
            name: 'MaxRate'
        },
        {
            type: 'float',
            name: 'WithHoldTaxAmount'
        },
        {
            type: 'float',
            name: 'CommissionTerm'
        },
        {
            type: 'int',
            name: 'MaxTerm'
        },
        {
            type: 'float',
            name: 'NetPaid'
        },
        {
            type: 'float',
            name: 'CommissionVATNo'
        },
        {
            type: 'float',
            name: 'InterestRate'
        },
        {
            type: 'date',
            name: 'CommissionVATDate'
        },
        {
            type: 'float',
            name: 'LowInterestRate'
        },
        {
           
            name: 'CampaignName'
        }
        


    ]
});