/*
 * File: app/view/main/mainmarketing/window/CommInsWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.CommInsWindow', {
    extend: 'Ext.panel.Panel',
    //alias: 'widget.mainmainmarketingwindowcomminswindow',
    alias: 'widget.comminstab',

    requires: [
        'FrontHPApp.view.main.mainmarketing.window.CommInsWindowViewModel',
        'FrontHPApp.view.main.mainmarketing.window.CommInsWindowViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging'
    ],

    controller: 'mainmainmarketingwindowcomminswindow',
    viewModel: {
        type: 'mainmainmarketingwindowcomminswindow'
    },
    autoShow: true,
    layout: 'border',
    title: '',

    items: [
        {
            xtype: 'form',
            region: 'north',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'fieldset',
                    itemId: 'frmComIns',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 175,
                        width: '100%'
                    },
                    title: 'Comm. Insurance',
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            colspan: 2,
                            height: '',
                            margin: '5 0 0 0',
                            width: 562,
                            layout: 'table',
                            fieldLabel: 'ENTCODE',
                           
                            items: [
                                {
                                    xtype: 'textfield',
                                    emptyText: '[ENTCODE]',
                                    name: 'EntCodeShow'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 5 5 5',
                                    iconCls: 'icon-find',
                                    tooltip: 'ค้นหาข้อมูลผู้แนะนำ',
                                    listeners: {
                                        click: 'onSelectEntCodeClick'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    width: '',
                                    fieldLabel: '',
                                    name: 'EntNameShow',
                                    emptyText: '[ENTNAME]'
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            width: 351,
                            fieldLabel: 'Commission Amount',
                            name: 'CommissionAmount',
                            emptyText: '[Commission Amount]'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            width: 351,
                            fieldLabel: 'Pay Commissiom To',
                            name: 'PayCommissionTo',
                            emptyText: '[Pay Commissiom To]'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            width: 351,
                            fieldLabel: 'VAT',
                            name: 'VAT',
                            emptyText: '[VAT]'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            width: 351,
                            fieldLabel: 'Absorb Tax',
                            name: 'AbsorbTax',
                            emptyText: '[Absorb Tax]'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            width: 351,
                            fieldLabel: 'Amount Include VAT',
                            name: 'AmountIncludeVAT',
                            emptyText: '[Amount Include VAT]'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            width: 351,
                            fieldLabel: 'With Hold Tax Amount',
                            name: 'WithHoldTaxAmount',
                            emptyText: '[With Hold Tax Amount]'
                        },
                        {
                            xtype: 'numberfield',
                            colspan: 2,
                            width: 351,
                            fieldLabel: 'Net Paid',
                            name: 'NetPaid',
                            emptyText: '[Net Paid]'
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            margin: '0 5 0 5',
                            iconCls: 'icon-save',
                            text: 'บันทึกข้อมูล',
                            listeners: {
                                click: 'onSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-reset',
                            text: 'เคลียร์',
                            listeners: {
                                click: 'onClearClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            flex: 1,
            region: 'center',
            itemId: 'GridComIns',
            title: 'ข้อมูล Comm. Insuramce',
            store: 'comInsModels',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 50,
                    align: 'center',
                    dataIndex: 'ID',
                    text: '#',
                    tooltip: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'DealerName',
                    text: 'DealerName',
                    flex: -1
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'PayCommissionTo',
                    text: 'Pay Commission To '
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function (value, metaData, record, rowIndex, colIndex, store, view) {
                        var accept = 'resources/icons/accept.gif',
                            not_accept = 'resources/icons/cross.gif';

                        if (!value) { //change the resource below :
                            return '<img src="' + accept + '" />';
                        } else {
                            return '<img src="' + not_accept + '" />';
                        }
                    },
                    dataIndex: 'AbsorbTax',
                    text: 'Absorb Tax '
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Commission',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'CommissionAmount',
                            text: 'Commission Amount '
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 80,
                            dataIndex: 'VAT',
                            text: 'VAT'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'AmountIncludeVAT',
                            text: 'Amount Include VAT '
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 170,
                            dataIndex: 'WithHoldTaxAmount',
                            text: 'With Hold Tax Amount '
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'NetPaid',
                            text: 'Net Paid '
                        },
                    {

                            xtype: 'hiddenfield',
                            name: 'id',
                            value: '0'
                            },
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-edit',
                            text: 'แก้ไข',
                            listeners: {
                                click: 'onEditClick'
                            }
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-delete',
                            text: 'ลบ',
                            listeners: {
                                click: 'onDeleteClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    displayInfo: true,
                    store: 'comInsModels',
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            },
            listeners: {
                itemdblclick: 'onItemDblClick'
            }
        }
    ]

});