/*
 * File: app/view/main/mainmarketing/window/GarantorWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.GarantorWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainmainmarketingwindowgarantorwindow',

    requires: [
        'FrontHPApp.view.main.mainmarketing.window.GarantorWindowViewModel',
        'FrontHPApp.view.main.mainmarketing.window.GarantorWindowViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Display',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging'
    ],

    controller: 'mainmainmarketingwindowgarantorwindow',
    viewModel: {
        type: 'mainmainmarketingwindowgarantorwindow'
    },
    scrollable: true,
    title: 'ข้อมูลผู้ค้ำประกัน',

    items: [
        {
            xtype: 'form',
            reference: 'form',
            itemId: 'myform1',
            scrollable: true,
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 190
                    },
                    title: 'ข้อมูลผู้ค้ำประกัน',
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'เลขที่บัตรประชาชน',
                            labelCls: 'text-require',
                            name: 'CID',
                            allowBlank: false,
                            emptyText: '[เลขที่บัตรประชาชน]'
                        },
                        {
                            xtype: 'fieldcontainer',
                            colspan: 2,
                            layout: 'table',
                            fieldLabel: '',
                            labelAlign: 'right',
                            labelWidth: 200,
                            items: [
                                {
                                    xtype: 'combobox',
                                    afterLabelTextTpl: [
                                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                    ],
                                    fieldLabel: 'ชื่อ-นามสกุลผู้ต้ำประกัน',
                                    labelAlign: 'right',
                                    labelCls: 'text-require',
                                    labelWidth: 190,
                                    name: 'GurantorTitleName',
                                    allowBlank: false,
                                    emptyText: '[เลือก]',
                                    displayField: 'name',
                                    store: 'commonModels',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    name: 'GarantorName',
                                    allowBlank: false,
                                    emptyText: '[ชื่อ]'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 185,
                                    fieldLabel: '',
                                    name: 'GarantorSurName',
                                    allowBlank: false,
                                    emptyText: '[นามสกุล]'
                                }
                            ]
                        },
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'วัน/เดือน/ปีเกิด',
                            labelCls: 'text-require',
                            name: 'BirthDate',
                            allowBlank: false,
                            emptyText: '[วัน/เดือน/ปีเกิด]'
                        },
                        {
                            xtype: 'fieldcontainer',
                            layout: 'table',
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 230,
                                    fieldLabel: 'อายุ',
                                    labelAlign: 'right',
                                    labelWidth: 190,
                                    name: 'GurantorTitleName',
                                    emptyText: '[ปี]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'ปี'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 50,
                                    fieldLabel: '',
                                    name: 'GarantorName',
                                    emptyText: '[เดือน]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'เดือน'
                                }
                            ]
                        },
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'วันที่บัตรหมดอายุ',
                            name: 'CardExpireDate',
                            emptyText: '[วันที่บัตรหมดอายุ]'
                        },
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'วันที่ออกบัตร',
                            labelCls: 'text-require',
                            name: 'CardExpireDate',
                            allowBlank: false,
                            emptyText: '[วันที่ออกบัตร]'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'สถานที่ออกบัตร',
                            name: 'CID',
                            emptyText: '[สถานที่ออกบัตร]'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'สัญชาติ',
                            name: 'CID',
                            allowBlank: false,
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'commonModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'เชื้อชาติ',
                            allowBlank: false,
                            emptyText: '[เชื้อชาติ]',
                            displayField: 'name',
                            store: 'commonModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'radiogroup',
                            width: 326,
                            fieldLabel: 'เพศ',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'rdSex',
                                    boxLabel: 'ชาย'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'rdSex',
                                    boxLabel: 'หญิง'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 190
                    },
                    title: 'ความสัมพันธ์กับผู้เช่าซื้อ',
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'ความสัมพันธ์กับผู้เช่าซื้อ',
                            labelCls: 'text-require',
                            name: 'CID',
                            allowBlank: false,
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'commonModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'เบอร์โทรศัพท์พื้นฐาน',
                            name: 'BirthDate',
                            emptyText: '[เบอร์โทรศัพท์พื้นฐาน]'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'เบอร์โทรศัพท์มือถือ',
                            name: 'CardExpireDate',
                            emptyText: '[เบอร์โทรศัพท์มือถือ]'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'ลักษณะที่พักอาศัย',
                            name: 'CardExpireDate',
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'commonModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'ระบุ',
                            name: 'CardExpireDate',
                            emptyText: '[ระบุ]'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'ที่อยู่ปัจจุบันตรงตามทะเบียนบ้าน',
                            name: 'CardExpireDate',
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'commonModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'fieldcontainer',
                            layout: 'table',
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 230,
                                    fieldLabel: 'ระยะเวลาที่พักอาศัย',
                                    labelAlign: 'right',
                                    labelWidth: 190,
                                    name: 'GurantorTitleName',
                                    emptyText: '[ปี]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'ปี'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 50,
                                    fieldLabel: '',
                                    name: 'GarantorName',
                                    emptyText: '[เดือน]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'เดือน'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            colspan: 2,
                            fieldLabel: 'สถานะตามทะเบียนบ้าน',
                            name: 'CID',
                            allowBlank: false,
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'commonModels',
                            valueField: 'id'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 190
                    },
                    title: 'ข้อมูลอาชีพ',
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            layout: 'table',
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 225,
                                    fieldLabel: 'อายุงานรวม',
                                    labelAlign: 'right',
                                    labelWidth: 190,
                                    name: 'GurantorTitleName',
                                    emptyText: '[ปี]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'ปี'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 50,
                                    fieldLabel: '',
                                    name: 'GarantorName',
                                    emptyText: '[เดือน]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'เดือน'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            colspan: 2,
                            layout: 'table',
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 225,
                                    fieldLabel: 'อายุงานปัจจุบัน',
                                    labelAlign: 'right',
                                    labelWidth: 190,
                                    name: 'GurantorTitleName',
                                    emptyText: '[ปี]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'ปี'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 50,
                                    fieldLabel: '',
                                    name: 'GarantorName',
                                    emptyText: '[เดือน]'
                                },
                                {
                                    xtype: 'displayfield',
                                    margin: '0 5 5 5',
                                    fieldLabel: '',
                                    value: 'เดือน'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'หมวดอาชีพ',
                            name: 'CID',
                            allowBlank: false,
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'occupationCatelogyModels',
                            valueField: 'OccupationCatelogy_id'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'กลุ่มอาชีพ',
                            name: 'BirthDate',
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'occupationGroupModels',
                            valueField: 'OccupationGroup_id'
                        },
                        {
                            xtype: 'combobox',
                            width: '',
                            fieldLabel: 'ประเภทอาชีพ',
                            name: 'CardExpireDate',
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'occupationTypeModels',
                            valueField: 'OccupationCareer_id'
                        },
                        {
                            xtype: 'combobox',
                            width: '',
                            fieldLabel: 'ตำแหน่ง',
                            name: 'CardExpireDate',
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'positionModels',
                            valueField: 'Position_id'
                        },
                        {
                            xtype: 'textfield',
                            width: '',
                            fieldLabel: 'สถานที่ทำงาน',
                            name: 'CardExpireDate',
                            emptyText: '[สถานที่ทำงาน]'
                        },
                        {
                            xtype: 'textfield',
                            width: '',
                            fieldLabel: 'รายละเอียดอาชีพ',
                            name: 'CardExpireDate',
                            emptyText: '[รายละเอียดอาชีพ]'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 190
                    },
                    title: 'รายละเอียดคู่สมรส',
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'ชื่อ/สกุล',
                            name: 'CID',
                            emptyText: '[ชื่อ/สกุล]'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'กลุ่มอาชีพ',
                            name: 'CID',
                            allowBlank: false,
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'occupationGroupModels',
                            valueField: 'OccupationGroup_id'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'สถานที่ทำงาน',
                            name: 'CID',
                            emptyText: '[สถานที่ทำงาน]'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'รายได้',
                            name: 'CID',
                            emptyText: '[รายได้]'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'ตำแหน่ง',
                            name: 'CID',
                            emptyText: '[ตำแหน่ง]'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'อายุงาน',
                            name: 'CID',
                            emptyText: '[อายุงาน]'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'โทรศัพท์',
                            name: 'CID',
                            emptyText: '[โทรศัพท์]'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'ค่าใช้จ่ายต่อเดือน',
                            name: 'BirthDate',
                            emptyText: '[ค่าใช้จ่ายต่อเดือน]'
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    fieldLabel: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            margins: '',
                            margin: '0 5 0 5',
                            iconCls: 'icon-save',
                            text: 'บันทึกข้อมูล',
                            listeners: {
                                click: 'onSaveAddressClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margins: '',
                            margin: '0 5 0 5',
                            iconCls: 'icon-address',
                            text: 'บันทึกข้อมูลที่อยู่',
                            listeners: {
                                click: 'onSaveAddressClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'icon-card',
                            text: 'บันทึกข้อมูลบัตร',
                            listeners: {
                                click: 'onSaveCardClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            itemId: 'GridGarantor',
            collapsible: false,
            title: 'ข้อมูลผู้ค้ำประกัน',
            store: 'gurantorGridModels',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 45,
                    align: 'center',
                    text: '#',
                    tooltip: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    width: '',
                    dataIndex: 'CiticenId',
                    text: 'เลขที่บัตรประชาชน'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Name',
                    text: 'ชื่อ-นามสกุลผู้ค้ำประกัน',
                    flex: -1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CusRelationShip',
                    text: 'ความสัมพันธ์ผู้เช่าซื้อ'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.Date.format(value, 'd/m/Y');
                    },
                    dataIndex: 'BirthDate',
                    text: 'วัน/เดือน/ปีเกิด'
                },
                {
                    xtype: 'gridcolumn',
                    width: 140,
                    dataIndex: 'Tel',
                    text: 'เบอร์โทรศัพท์พื้นฐาน'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-edit',
                            text: 'แก้ไข',
                            listeners: {
                                click: 'onEditGridClick'
                            }
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-delete',
                            text: 'ลบ',
                            listeners: {
                                click: 'onDeleteGridClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 380,
                    displayInfo: true
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            },
            listeners: {
                itemdblclick: 'onGridGarantorItemDblClick'
            }
        }
    ]

});