/*
 * File: app/view/main/mainmarketing/window/SubsidyWindowViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.SubsidyWindowViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.mainmainmarketingwindowsubsidywindow',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        subsidyViewModels: {
            model: 'FrontHPApp.model.SubsidyViewModel',
            data: [
                {
                    id: 26,
                    Detail: 'numquam',
                    DESC: 'vel',
                    Amount: 751.73
                },
                {
                    id: 882,
                    Detail: 'reiciendis',
                    DESC: 'sunt',
                    Amount: 557.4
                },
                {
                    id: 638,
                    Detail: 'explicabo',
                    DESC: 'est',
                    Amount: 198.81
                },
                {
                    id: 841,
                    Detail: 'similique',
                    DESC: 'magni',
                    Amount: 731.85
                },
                {
                    id: 437,
                    Detail: 'doloremque',
                    DESC: 'odit',
                    Amount: 764.28
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});