/*
 * File: app/view/main/mainmarketing/window/SubsidyWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.SubsidyWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainmainmarketingwindowsubsidywindow',

    requires: [
        'FrontHPApp.view.main.mainmarketing.window.SubsidyWindowViewModel',
        'FrontHPApp.view.main.mainmarketing.window.SubsidyWindowViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.XTemplate',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.button.Button',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Paging',
        'Ext.grid.feature.Summary'
    ],

    controller: 'mainmainmarketingwindowsubsidywindow',
    viewModel: {
        type: 'mainmainmarketingwindowsubsidywindow'
    },
    scrollable: false,
    layout: 'border',
    iconCls: 'icon-details',
    title: 'SUBSIDY',

    items: [
        {
            xtype: 'form',
            region: 'north',
            reference: 'form',
            itemId: 'myform1',
            scrollable: true,
            bodyPadding: 15,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelAlign: 'left',
                        labelWidth: 250
                    },
                    title: 'Subsidy',
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: '',
                            value: 'Pay Deduct'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: '',
                            emptyText: 'เลือก',
                            displayField: 'Name',
                            store: 'combo.PayDeductStore',
                            valueField: 'id'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '',
                            value: 'Hire purchase Amount'
                        },
                        {
                            xtype: 'numberfield',
                            width: 100,
                            fieldLabel: '',
                            name: '',
                            emptyText: '[Hire purchase Amount]'
                        },
                        {
                            xtype: 'displayfield',
                            width: 400,
                            fieldLabel: '<span style="color:red;font-weight:bold">Net Flat Rate % (อัตราดอกเบี้ยมาตรฐาน)</span>',
                            value: ''
                        },
                        {
                            xtype: 'numberfield',
                            width: 100,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: '',
                            name: '',
                            allowBlank: false,
                            emptyText: '[Net Flat Rate % (อัตราดอกเบี้ยมาตรฐาน)]'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '',
                            value: 'Fin.Amount (Subsidy)'
                        },
                        {
                            xtype: 'numberfield',
                            width: 100,
                            fieldLabel: '',
                            emptyText: '[Fin.Amount (Subsidy)]'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '',
                            value: 'Subsidy Amount'
                        },
                        {
                            xtype: 'numberfield',
                            width: 100,
                            fieldLabel: '',
                            emptyText: '[Subsidy Amount]'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '',
                            value: 'Subsidy Net Amount (Net VAT)'
                        },
                        {
                            xtype: 'numberfield',
                            width: 100,
                            fieldLabel: '',
                            emptyText: '[Subsidy Net Amount (Net VAT)]'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '',
                            value: 'W/H TAX Amount'
                        },
                        {
                            xtype: 'numberfield',
                            width: 100,
                            fieldLabel: '',
                            emptyText: '[W/H TAX Amount]'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '',
                            value: 'Paid Amount'
                        },
                        {
                            xtype: 'numberfield',
                            width: 100,
                            fieldLabel: '',
                            emptyText: '[W/H TAX Amount]'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    itemId: 'GridSubsidy',
                    iconCls: 'icon-details',
                    title: 'ข้อมูล Subsidy',
                    store: 'sunsidyModels',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 50,
                            align: 'center',
                            text: '#',
                            tooltip: 'ลำดับ'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'List',
                            text: 'รายการ',
                            editor: {
                                xtype: 'combobox',
                                emptyText: 'เลือก',
                                displayField: 'Name',
                                store: 'combo.ListSubsidyStore',
                                valueField: 'id'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            summaryRenderer: function(val, params, data) {
                                return '<span style="color:black;font-weight:bold">รวม</span>';
                            },
                            summaryType: 'count',
                            dataIndex: 'Detail',
                            text: 'รายละเอียด',
                            flex: -1,
                            editor: {
                                xtype: 'textfield',
                                emptyText: 'รายละเอียด'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            summaryRenderer: function(val, params, data) {
                                return '<span style="color:black;font-weight:bold">'+Ext.util.Format.number(val,'0.00')+'</span>';
                            },
                            summaryType: 'sum',
                            dataIndex: 'Amount',
                            text: 'จำนวนเงิน',
                            editor: {
                                xtype: 'numberfield',
                                width: 50,
                                fieldLabel: 'Label',
                                emptyText: 'จำนวนเงิน'
                            }
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    ui: 'default-small',
                                    iconCls: 'icon-add',
                                    text: 'เพิ่ม',
                                    listeners: {
                                        click: 'onAddClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    ui: 'default-small',
                                    iconCls: 'icon-edit',
                                    text: 'แก้ไข',
                                    listeners: {
                                        click: 'onEditClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    ui: 'default-small',
                                    iconCls: 'icon-delete',
                                    text: 'ลบ',
                                    listeners: {
                                        click: 'onDeleteClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            hidden: true,
                            displayInfo: true
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'rowediting'
                        }
                    ],
                    features: [
                        {
                            ftype: 'summary'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    margin: '15 0 15 0',
                    layout: {
                        type: 'hbox',
                        align: 'bottom',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'บันทึกข้อมูล'
                        },
                        {
                            xtype: 'button',
                            margin: '0 5 0 5',
                            text: 'ลบข้อมูล'
                        }
                    ]
                }
            ]
        }
    ]

});