/*
 * File: app/view/main/mainmarketing/window/TypeCardWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.TypeCardWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainmainmarketingwindowtypecardwindow',

    requires: [
        'FrontHPApp.view.FrmGarantorViewModel2',
        'FrontHPApp.view.FrmGarantorViewController2',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging'
    ],

    controller: 'mainmainmarketingwindowtypecardwindow',
    viewModel: {
        type: 'mainmainmarketingwindowtypecardwindow'
    },
    layout: 'border',
    title: 'ประเภทบัตร',

    items: [
        {
            xtype: 'form',
            region: 'north',
            reference: 'form',
            itemId: 'myform1',
            scrollable: true,
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 190
                    },
                    title: 'ประเภทบัตร',
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            colspan: 2,
                            width: 367,
                            fieldLabel: 'ประเภทลูกค้า',
                            labelAlign: 'right',
                            labelWidth: 190,
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'typeCustomerModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            width: 367,
                            fieldLabel: 'ประเภทบัตร',
                            labelAlign: 'right',
                            labelWidth: 190,
                            emptyText: '[เลือก]',
                            displayField: 'name',
                            store: 'commonModels',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'หมายเลขบัตร',
                            name: '',
                            emptyText: '[หมายเลขบัตร]'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'Issue Date',
                            labelAlign: 'right',
                            labelWidth: 190,
                            name: '',
                            emptyText: '[วว/ดด/ปปปป]',
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'Expire Date',
                            emptyText: '[วว/ดด/ปปปป]',
                            format: 'd/m/Y'
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    fieldLabel: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-save',
                            text: 'บันทึก',
                            listeners: {
                                click: 'onSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '0 5 0 5',
                            iconCls: 'icon-reset',
                            text: 'เคลียร์',
                            listeners: {
                                click: 'onClearClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            region: 'center',
            itemId: 'GridCard',
            collapsible: false,
            iconCls: 'icon-details',
            title: 'ข้อมูลประเภทบัตร',
            store: 'typeCardModels',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 45,
                    align: 'center',
                    text: '#',
                    tooltip: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    width: '',
                    dataIndex: 'TypeCard',
                    text: 'ประเภทบัตร',
                    flex: -1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CardId',
                    text: 'หมายเลขบัตร'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.Date.format(value, 'd/m/Y');
                    },
                    dataIndex: 'IssueDate',
                    text: 'Issue Date'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.Date.format(value, 'd/m/Y');
                    },
                    dataIndex: 'ExpireDate',
                    text: 'Expire Date'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            hidden: true,
                            ui: 'default-small',
                            text: 'เพิ่ม'
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-edit',
                            text: 'แก้ไข',
                            listeners: {
                                click: 'onEditGridClick'
                            }
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-delete',
                            text: 'ลบ',
                            listeners: {
                                click: 'onDeleteClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ]

});