/*
 * File: app/view/main/maincheckdoc/CheckDocumentTab.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.maincheckdoc.CheckDocumentTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mainmaincheckdoccheckdocumenttab',

    requires: [
        'FrontHPApp.view.main.maincheckdoc.CheckDocumentTabViewModel',
        'FrontHPApp.view.main.maincheckdoc.CheckDocumentTabViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.toolbar.Paging',
        'Ext.form.field.Display',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea'
    ],

    controller: 'mainmaincheckdoccheckdocumenttab',
    viewModel: {
        type: 'mainmaincheckdoccheckdocumenttab'
    },
    scrollable: false,
    layout: 'border',
    title: 'ตรวจสอบเอกสาร',

    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            reference: 'form',
            itemId: 'myform1',
            bodyPadding: 10,
            iconCls: 'icon-details',
            title: 'ค้นหาข้อมูล',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'panel',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 130,
                       
                    },
                    title: '',
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'วันที่ใบคำขอจาก',
                            labelAlign: 'right',
                            allowBlank: false,
                            emptyText: '[วว/ดด/ปปปป]'
                        },
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'ถึงวันที่ใบคำขอ',
                            labelAlign: 'right',
                            allowBlank: false,
                            emptyText: '[วว/ดด/ปปปป]'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'ชื่อ-นามสกุลผู้เช่าซื้อ',
                            labelAlign: 'right',
                            emptyText: '[ชื่อ-นามสกุลผู้เช่าซื้อ]'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'สถานะใบคำขอ',
                            labelAlign: 'right',
                            emptyText: '[เลือก]',
                            displayField: 'Name',
                            width: 390,
                            store: 'combo.RequestStatusStore',
                            valueField: 'Id'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            fieldLabel: 'เลขที่ใบคำขอ',
                            labelAlign: 'right',
                            emptyText: '[เลขที่ใบคำขอ]'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                           
                            fieldLabel: 'เลขที่บัตรประชาชน',
                            labelAlign: 'right',
                            emptyText: '[เลขที่บัตรประชาชน]'
                        },
                        {
                            xtype: 'combobox',
                            colspan: 2,
                            fieldLabel: 'สาขา',
                            labelAlign: 'right',
                            emptyText: '[เลือก]',
                            displayField: 'Name',
                            store: 'combo.BranchStore',
                            valueField: 'id'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'container',
                            colspan: 2,
                           
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '',
                                    margin: '0 5 0 5',
                                    iconCls: 'icon-find',
                                    text: 'ค้นหาข้อมูล',
                                  
                                    listeners: {
                                        click: 'onFindClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-reset',
                                    text: 'เคลียร์',
                                    listeners: {
                                        click: 'onClearClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'panel',
            region: 'center',
            split: false,
            items: [
                {
                    xtype: 'gridpanel',
                    scrollable: true,
                    collapsible: false,
                    iconCls: 'icon-details',
                    title: 'ข้อมูลเอกสารแนบ',
                    store: 'checkPaperModels',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 45,
                            align: 'center',
                            text: '#',
                            tooltip: 'ลำดับ'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: '',
                            dataIndex: 'RequestNo',
                            lockable: false,
                            text: 'เลขที่ใบคำขอ'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return Ext.Date.format(value, 'd/m/Y');
                            },
                            width: '',
                            dataIndex: 'RequestDate',
                            lockable: false,
                            text: 'วันที่ใบคำขอ'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 121,
                            dataIndex: 'IdApprove',
                            lockable: false,
                            text: 'เลขที่อนุมัติ'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 194,
                            defaultWidth: 200,
                            dataIndex: 'CitizenId',
                            text: 'เลขที่บัตรประชาชน'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'CusName',
                            text: 'ชื่อ-นามสกุลผู้เช่าซื้อ'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'TypeLoan',
                            text: 'ประเภทสินเชื่อ'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'BranchName',
                            text: 'สาขา'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'National',
                            text: 'สัญชาตื'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'checkPaperModels'
                        }
                    ],
                    listeners: {
                        selectionchange: 'onGridpanelSelectionChange'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'form',
                    dock: 'right',
                    itemId: 'form2',
                    margin: '0 0 0 5',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 175
                    },
                    layout: 'auto',
                    bodyPadding: 5,
                    title: 'ตรวจสอบเอกสารแนบ',
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'วันที่ใบคำขอ',
                            name: 'RequestDate'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'เลขที่ใบคำขอ',
                            name: 'RequestNo'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'ชื่อ-นามสกุลผู้เช่าซื้อ',
                            name: 'CusName'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'ประเภทสินเชื่อ',
                            name: 'TypeLoan'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'สาขา',
                            name: 'BranchName'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'เอกสารแนบ 1',
                            name: 'Doc1',
                            readOnly: true,
                            emptyText: '[เอกสารแนบ 1]'
                        },
                        {
                            xtype: 'container',
                            margin: '0 0 0 75',
                            width: '80%',
                            layout: 'table',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'เอกสารแนบ 2',
                                    labelAlign: 'right',
                                    name: 'Doc3',
                                    readOnly: true,
                                    emptyText: '[เอกสารแนบ 2]'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    margin: '0 5 5 5',
                                    iconCls: 'icon-add',
                                    text: 'เพิ่มเอกสาร',
                                    listeners: {
                                        click: 'onInsertDocClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            width: 300,
                            layout: 'table',
                            items: [
                                {
                                    xtype: 'radiogroup',
                                    width: 500,
                                    fieldLabel: 'ผลการตรวจสอบเอกสาร',
                                    labelAlign: 'right',
                                    labelWidth: 174,
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'IdApprove',
                                            boxLabel: 'ผ่านการตรวจสอบ',
                                            checked: true,
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            labelWidth: 250,
                                            name: 'IdApprove',
                                            boxLabel: 'ไม่ผ่านการตรวจสอบ',
                                            inputValue: '2'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'textareafield',
                            width: 467,
                            fieldLabel: 'หมายเหตุ',
                            name: 'Remark',
                            emptyText: '[หมายเหตุ]'
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '0 5 0 180',
                                    iconCls: 'icon-save',
                                    text: 'บันทึกข้อมูล',
                                    listeners: {
                                        click: 'onSaveClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    iconCls: 'icon-cancel',
                                    text: 'ยกเลิก',
                                    listeners: {
                                        click: 'onCancelClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});