/*
 * File: app/view/main/mainmarketing/window/commonpopup/PopupDealerViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.commonpopup.PopupDealerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainmainmarketingwindowcommonpopuppopupdealer',

    onFindClick: function(button, e, eOpts) {
        var me = this,
           views = this.getView(),
           form = views.down('form').getForm(),
           store = views.down('grid').getStore();

        store.getProxy().setExtraParam('dealercode', form.findField('QDealerCode').getValue());
        store.getProxy().setExtraParam('dealername', form.findField('QDealerName').getValue());
        store.load();
       
    },

    onClearClick: function(button, e, eOpts) {
        var me = this.getView(),
           form = me.down('form');

        paging = me.down('pagingtoolbar'),
        store = paging.getStore();
        store.getProxy().extraParams = {};
        form.reset();
        store.load();
    },
     //[20150801] add by p2p
    onItemDblClick: function (dataview, record, item, index, e, eOpts) {

    this.getView().close();
    }

});
