/*
 * File: app/view/main/mainmarketing/window/commonpopup/PopupTypeCard.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.commonpopup.PopupTypeCard', {
    extend: 'Ext.window.Window',
    alias: 'widget.mainmainmarketingwindowcommonpopuppopuptypecard',

    requires: [
        'FrontHPApp.view.main.mainmarketing.window.commonpopup.PopupTypeCardViewModel',
        'FrontHPApp.view.main.mainmarketing.window.commonpopup.PopupTypeCardViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.XTemplate',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel'
    ],

    controller: 'mainmainmarketingwindowcommonpopuppopuptypecard',
    viewModel: {
        type: 'mainmainmarketingwindowcommonpopuppopuptypecard'
    },
    autoShow: true,
    width: 800,
    title: 'ค้นหาข้อมูลประเภทบัตร',
    titleAlign: 'center',

    items: [
        {
            xtype: 'form',
            reference: 'form',
            itemId: 'myform1',
            scrollable: true,
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 190
                    },
                    bodyPadding: 5,
                    iconCls: 'icon-details',
                    title: 'ประเภทบัตร',
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'ประเภทบัตร',
                            name: 'TypeCard',
                            emptyText: '[เลือก]',
                            displayField: 'Name',
                            store: 'combo.TypeCardStore',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            fieldLabel: 'หมายเลขบัตร',
                            name: 'CardNo',
                            emptyText: '[หมายเลขบัตร]'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: 'Issue Date',
                            name: 'IssueDate',
                            emptyText: '[Issue Date]'
                        },
                        {
                            xtype: 'datefield',
                            afterLabelTextTpl: [
                                ' '
                            ],
                            fieldLabel: 'Expire Date',
                            name: 'ExpireDate',
                            emptyText: '[Expire Date]'
                        },
                        {
                            xtype: 'hiddenfield',
                            name: 'id',
                            value: '0'
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    fieldLabel: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-save',
                            text: 'บันทึกข้อมูล',
                            listeners: {
                                click: 'onSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '0 5 0 5',
                            iconCls: 'icon-reset',
                            text: 'เคลียร์',
                            listeners: {
                                click: 'onClearClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            itemId: 'GridComSpacial',
            scrollable: true,
            collapsible: false,
            iconCls: 'icon-details',
            title: 'ข้อมูลประเภทบัตร',
            store: 'typePopupCardModels',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 45,
                    align: 'center',
                    text: '#',
                    tooltip: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TypeCard',
                    text: 'ประเภทบัตร'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CardNo',
                    text: 'หมายเลขบัตร',
                    flex: -1
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.Date.format(value, 'd/m/Y');
                    },
                    dataIndex: 'IssueDate',
                    text: 'Issue Date'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.Date.format(value, 'd/m/Y');
                    },
                    dataIndex: 'ExpireDate',
                    text: 'Expire Date'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            hidden: true,
                            ui: 'default-small',
                            text: 'เพิ่ม'
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-edit',
                            text: 'แก้ไข',
                            listeners: {
                                click: 'onEditClick'
                            }
                        },
                        {
                            xtype: 'button',
                            ui: 'default-small',
                            iconCls: 'icon-delete',
                            text: 'ลบ',
                            listeners: {
                                click: 'onDeleteClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    store:'typePopupCardModels',
                    displayInfo: true
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ]

});