/*
 * File: app/view/Tab2/window/FrmPopupBrowsePaper.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.Tab2.window.FrmPopupBrowsePaper', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tab2windowfrmpopupbrowsepaper',

    requires: [
        'FrontHPApp.view.FrmGarantorViewModel8',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'tab2windowfrmpopupbrowsepaper'
    },
    scrollable: false,
    layout: 'border',
    title: 'เลือกเอกสารอื่นๆ',

    items: [
        {
            xtype: 'form',
            flex: 1,
            region: 'center',
            reference: 'form',
            itemId: 'myform1',
            scrollable: true,
            bodyPadding: 10,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'fieldset',
                    defaults: {
                        labelAlign: 'right',
                        labelWidth: 190
                    },
                    title: 'เอกสารอื่นๆ',
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            width: 367,
                            fieldLabel: 'เลขที่ใบคำขอ',
                            labelAlign: 'right',
                            labelWidth: 190
                        },
                        {
                            xtype: 'datefield',
                            width: 367,
                            fieldLabel: 'ประเภทเอกสาร',
                            labelAlign: 'right',
                            labelWidth: 190
                        },
                        {
                            xtype: 'textfield',
                            width: 367,
                            fieldLabel: 'เอกสาร',
                            labelAlign: 'right',
                            labelWidth: 190
                        },
                        {
                            xtype: 'combobox',
                            width: 367,
                            fieldLabel: 'หมายเหตุ',
                            labelAlign: 'right',
                            labelWidth: 190
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    fieldLabel: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'แนบเอกสาร'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            flex: 2,
            region: 'south',
            split: true,
            height: 150,
            collapsible: true,
            title: 'ข้อมูลเอกสารแนบ',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 45,
                    text: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    width: '',
                    text: 'เลขที่ใบคำขอ'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'เลขที่อนุมัติ'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'เลขที่บัตรประชาชน'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'ชื่อ-นามสกุลผู้เช่าซื้อ'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'ประเภทสินเชื่อ'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'สาขา'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'สัญชาตื'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'เพิ่ม'
                        },
                        {
                            xtype: 'button',
                            text: 'แก้ไข'
                        },
                        {
                            xtype: 'button',
                            text: 'ลบ'
                        }
                    ]
                }
            ]
        }
    ]

});