/*
 * File: app/view/main/mainmarketing/window/main/mainmarketing/window/main/mainmarketing/window/requestcustomer/RequestCustomerWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.view.main.mainmarketing.window.main.mainmarketing.window.main.mainmarketing.window.requestcustomer.RequestCustomerWindow', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainmainmarketingwindowmainmainmarketingwindowpopup',

    onFindLeadClick: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopuplead").show();
    },

    onButtonClickBranch: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopupmarketing").show();
    },

    onBtnMarketingClick: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopupmarketing").show();
    },

    onButtonClickDealer: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopupdealer").show();
    },

    onSaveAddressCusClick1: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopupcusaddress").show();
    },

    onSaveCardClick: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopuptypecard").show();
    },

    onButtonClickSaveRequest: function(button, e, eOpts) {
        Ext.MessageBox.confirm("Confirm","คุณต้องบันทึกรายการ",function(btn){

            if(btn == 'yes'){

                Ext.MessageBox.alert("Status","บันทึกข้อมูลแล้ว");
            }

        },this);
    },

    onSaveAddressCusClick: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopupcusaddress").show();
    },

    onCardCusClick: function(button, e, eOpts) {
        Ext.widget("mainmainmarketingwindowrequestcustomerpopuptypecard").show();
    },

    onButtonClickCancelRequest: function(button, e, eOpts) {
        var me = this.getView();
        me.reset();
        //console.log(me);
    }

});
