/*
 * File: app/model/Insurance/InsuranceModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.model.Insurance.InsuranceModel', {
    extend: 'Ext.data.Model',
    alias: 'model.insurancemodel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            name: 'RequestNo'
            
        },
        {
            type: 'string',
            name: 'Customer',
            maping: 'InsuranceModel.Customer'
        },
        {
            name: 'InsuranceBy'
        },
        {
            type: 'string',
            name: 'ConditionInsurance'
        },
        {
            name: 'InsuranceCompany'
        },
        {
            name: 'NoticeNo'
        },
        {
            name: 'NoticeBy'
        },
        {
            name: 'NotiDate'
        },
        {
            name: 'PoicyNo'
        },
        {
            name: 'SSStart'
        },
        {
            name: 'SSEnd'
        },
        {
            name: 'SSCost'
        },
        {
            name: 'SSFee'
        },
        {
            name: 'WHInsFee'
        },
        {
            name: 'Stamp'
        },
        {
            
            name: 'SSFeeCoect'
        },
        {
            name: 'Deduct'
        },
        {
            name: 'Driver'
        },
        {
            name: 'WhereRepair'
        },
        {
            name: 'DriverName1'
        },
        {
            name: 'DriverBirth1'
        },
        {
            name: 'DrivingC1'
        },
        {
            name: 'DriverName2'
        },
        {
            name: 'DriverBirth2'
        },
        {
            name: 'DrivingC2'
        },
        {
            name: 'SSCampaign'
        },
        {
            name: 'SSComm'
        },
        {
            name: 'SSDiscount'
        },
        {
            name: 'SSPromotion'
        },
        {
            name: 'SSPromotionDiscount'
        }
    ],

    hasOne: [
        {
            model: 'FrontHPApp.model.Insurance.CompulsoryModel',
            name: 'CompulsoryModel',
            associationKey: 'RequestNo',
            foreignKey: 'RequestNo'
        },
        {
            model: 'FrontHPApp.model.Insurance.LoanProtectionModel',
            name: 'CompulsoryModel',
            associationKey: 'RequestNo',
            foreignKey: 'RequestNo'
        }
    ]
});