/*
 * File: app/store/browsePaperMyModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.browsePaperMyModels', {
    extend: 'Ext.data.Store',
    alias: 'store.browsepapermymodels',

    requires: [
        'FrontHPApp.model.BrowsePaperMyModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'browsePaperMyModels',
            model: 'FrontHPApp.model.BrowsePaperMyModel',
            data: [
                {
                    IDNum: 'rerum',
                    TypePaper: 'qui',
                    Order: 'vel',
                    FileName: 'aliquid',
                    Delete: 'qui',
                    Remark: 'dolorum',
                    Date: '11/18/2006'
                },
                {
                    IDNum: 'velit',
                    TypePaper: 'quam',
                    Order: 'nobis',
                    FileName: 'nostrum',
                    Delete: 'consequatur',
                    Remark: 'nihil',
                    Date: '8/23/2002'
                },
                {
                    IDNum: 'neque',
                    TypePaper: 'sit',
                    Order: 'dolore',
                    FileName: 'similique',
                    Delete: 'qui',
                    Remark: 'eum',
                    Date: '6/17/2004'
                },
                {
                    IDNum: 'explicabo',
                    TypePaper: 'id',
                    Order: 'optio',
                    FileName: 'eaque',
                    Delete: 'et',
                    Remark: 'occaecati',
                    Date: '7/3/2008'
                },
                {
                    IDNum: 'ipsum',
                    TypePaper: 'nam',
                    Order: 'eaque',
                    FileName: 'quia',
                    Delete: 'pariatur',
                    Remark: 'atque',
                    Date: '6/15/2012'
                },
                {
                    IDNum: 'exercitationem',
                    TypePaper: 'deleniti',
                    Order: 'sed',
                    FileName: 'maxime',
                    Delete: 'ipsam',
                    Remark: 'voluptatum',
                    Date: '12/10/2013'
                },
                {
                    IDNum: 'beatae',
                    TypePaper: 'ut',
                    Order: 'dolore',
                    FileName: 'ut',
                    Delete: 'provident',
                    Remark: 'est',
                    Date: '6/7/2011'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});