/*
 * File: app/store/incomeMainModels.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FrontHPApp.store.incomeMainModels', {
    extend: 'Ext.data.Store',
    alias: 'store.incomemainmodels',

    requires: [
        'FrontHPApp.model.IncomeMainModel',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'incomeMainModels',
            model: 'FrontHPApp.model.IncomeMainModel',
            data: [
                {
                    IncomeMain_id: 268,
                    name: 'iusto'
                },
                {
                    IncomeMain_id: 656,
                    name: 'et'
                },
                {
                    IncomeMain_id: 797,
                    name: 'ipsum'
                },
                {
                    IncomeMain_id: 323,
                    name: 'sequi'
                },
                {
                    IncomeMain_id: 818,
                    name: 'saepe'
                },
                {
                    IncomeMain_id: 352,
                    name: 'eum'
                },
                {
                    IncomeMain_id: 415,
                    name: 'ratione'
                },
                {
                    IncomeMain_id: 147,
                    name: 'nulla'
                },
                {
                    IncomeMain_id: 508,
                    name: 'ab'
                },
                {
                    IncomeMain_id: 488,
                    name: 'est'
                },
                {
                    IncomeMain_id: 47,
                    name: 'eligendi'
                },
                {
                    IncomeMain_id: 124,
                    name: 'unde'
                },
                {
                    IncomeMain_id: 303,
                    name: 'quasi'
                },
                {
                    IncomeMain_id: 983,
                    name: 'et'
                },
                {
                    IncomeMain_id: 73,
                    name: 'praesentium'
                },
                {
                    IncomeMain_id: 854,
                    name: 'non'
                },
                {
                    IncomeMain_id: 199,
                    name: 'aut'
                },
                {
                    IncomeMain_id: 80,
                    name: 'ut'
                },
                {
                    IncomeMain_id: 386,
                    name: 'sed'
                },
                {
                    IncomeMain_id: 393,
                    name: 'in'
                },
                {
                    IncomeMain_id: 985,
                    name: 'quaerat'
                },
                {
                    IncomeMain_id: 208,
                    name: 'blanditiis'
                },
                {
                    IncomeMain_id: 571,
                    name: 'sapiente'
                },
                {
                    IncomeMain_id: 532,
                    name: 'modi'
                },
                {
                    IncomeMain_id: 235,
                    name: 'voluptatum'
                },
                {
                    IncomeMain_id: 136,
                    name: 'neque'
                },
                {
                    IncomeMain_id: 147,
                    name: 'ratione'
                },
                {
                    IncomeMain_id: 96,
                    name: 'nostrum'
                },
                {
                    IncomeMain_id: 337,
                    name: 'quia'
                },
                {
                    IncomeMain_id: 340,
                    name: 'libero'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});